import { Redirect, router, useFocusEffect } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { Screen } from '@/ui/screen';
import { BadgerMark } from '@/ui/badger-mark';
import { FadeInView } from '@/ui/motion';
import {useLiveVersion} from '@/live/live-context';
import { useAuth } from '@/auth/auth-context';
import { apiFetch } from '@/api/client';
import { API_OVERRIDE_ENABLED } from '@/api/api-endpoint-store';
import { colors, radii, themedStyleSheet, type ThemeMode } from '@/theme/tokens';
import { useAppTheme } from '@/theme/theme-context';
import {carrierLabel,loadDriverReadiness,type DriverReadiness} from '@/readiness/driver-readiness';

type ProfileData={verification?:{status:string};reputation?:{completedDeals:number;reviewCount:number;rating:number|null}};
export default function Profile(){const live=useLiveVersion('notifications');
  const{user,logout}=useAuth();const{mode,setMode}=useAppTheme();const[profile,setProfile]=useState<ProfileData|null>(null);const[readiness,setReadiness]=useState<DriverReadiness|null>(null);const[unread,setUnread]=useState(0);const devTap=useRef({count:0,last:0});
  useFocusEffect(useCallback(()=>{if(!user)return;void apiFetch('/users/me/profile').then(async r=>{if(r.ok)setProfile(await r.json())}).catch(()=>{});void loadDriverReadiness().then(setReadiness).catch(()=>{});void apiFetch('/notifications/unread-count').then(async r=>{if(r.ok)setUnread((await r.json()).count??0)}).catch(()=>{})},[user,live]));
  if(!user)return <Redirect href="/auth"/>;
  const rep=profile?.reputation;const signOut=async()=>{await logout();router.replace('/auth')};const revealDeveloperConnection=()=>{if(!API_OVERRIDE_ENABLED)return;const now=Date.now();devTap.current.count=now-devTap.current.last<1400?devTap.current.count+1:1;devTap.current.last=now;if(devTap.current.count>=5){devTap.current.count=0;router.push('/developer-connection')}};
  return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:112}}>
    <View style={s.header}><View><Text style={s.eyebrow}>ACCOUNT CENTER</Text><Text style={s.pageTitle}>Профіль</Text></View><Pressable onPress={revealDeveloperConnection} style={s.build}><Text style={s.buildText}>UI 1.8.3</Text></Pressable></View>
    <FadeInView><View style={s.hero}><View style={s.avatar}><Text style={s.avatarText}>{user.displayName.slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{user.displayName}</Text><Text style={s.email}>{user.phone??user.email??'—'}</Text><View style={s.verifyPill}><View style={s.verifyDot}/><Text style={s.verifyText}>{(profile?.verification?.status??user.verificationStatus).toUpperCase()}</Text></View></View></View></FadeInView>
    <FadeInView delay={45}><View style={s.stats}><Stat value={rep?.rating==null?'—':rep.rating.toFixed(2)} label="РЕЙТИНГ"/><Stat value={String(rep?.completedDeals??0)} label="ЗАВЕРШЕНО"/><Stat value={String(rep?.reviewCount??0)} label="ВІДГУКІВ"/></View></FadeInView>

    <Text style={s.sectionLabel}>ВИГЛЯД</Text>
    <FadeInView delay={80}><View style={s.themeCard}><View style={s.themeTitleRow}><View><Text style={s.cardTitle}>Тема інтерфейсу</Text><Text style={s.themeMeta}>Оберіть характер CargoGo</Text></View>{mode==='badger'&&<View style={s.signature}><BadgerMark size={28}/><Text style={s.signatureText}>SIGNATURE</Text></View>}</View><View style={s.themeGrid}>
      <ThemeOption mode="dark" current={mode} title="ТЕМНА" subtitle="CLASSIC" onPress={()=>void setMode('dark')}/>
      <ThemeOption mode="light" current={mode} title="СВІТЛА" subtitle="CLEAN" onPress={()=>void setMode('light')}/>
      <ThemeOption mode="badger" current={mode} title="BADGER" subtitle="SIGNATURE" onPress={()=>void setMode('badger')}/>
    </View><Text style={s.cardText}>Badger — фірмовий нічний режим: глибокий графіт, теплий маршрутний акцент і медоїд як знак руху CargoGo.</Text></View></FadeInView>

    <Text style={s.sectionLabel}>НАЛАШТУВАННЯ</Text>
    <MenuRow icon="@" title="Контакти та відновлення" meta="PHONE · EMAIL · BACKUP" onPress={()=>router.push('/account-contacts')}/>
    <MenuRow icon="◎" title="Готовність до перевезень" meta={readiness?.ready?'READY':`${readiness?.completed??0}/3 · ПОТРІБНА ДІЯ`} onPress={()=>router.push('/driver-readiness')}/><MenuRow icon="↗" title="Режим перевізника та правила" meta={carrierLabel(readiness)} onPress={()=>router.push('/carrier-mode')}/><MenuRow icon="₴" title="Оплата та виплати" meta="IBAN · payout" onPress={()=>router.push('/payout-settings')}/>
    <MenuRow icon="✓" title="Центр верифікації" meta={(profile?.verification?.status??user.verificationStatus).toUpperCase()} onPress={()=>router.push('/verification')}/>
    {(user.staffRole==='reviewer'||user.staffRole==='verification_reviewer'||user.staffRole==='admin')&&<MenuRow icon="ID" title="Черга верифікації" meta="STAFF" onPress={()=>router.push('/verification-review')}/>} 
    {(user.staffRole==='reviewer'||user.staffRole==='dispute_reviewer'||user.staffRole==='admin')&&<MenuRow icon="!" title="Спори" meta="STAFF" onPress={()=>router.push('/dispute-review')}/>} 
    <MenuRow icon="§" title="Правові документи" meta="TERMS · PRIVACY · PAYMENTS" onPress={()=>router.push('/legal')}/><MenuRow icon="P" title="Конфіденційність і дані" meta="ACCESS · DELETE · RETENTION" onPress={()=>router.push('/privacy-center')}/><MenuRow icon="•" title="Сповіщення" meta={unread?`${unread} НОВИХ`:'ВІДКРИТИ'} onPress={()=>router.push('/notifications')}/>
    <View style={s.info}><View style={s.infoHead}><BadgerMark size={28} quiet/><Text style={s.infoTitle}>TRUST LAYER</Text></View><Text style={s.cardText}>Рейтинг формується тільки завершеними угодами. Документальна KYC-перевірка лишається окремим захищеним потоком.</Text></View>
    <Pressable onPress={signOut} style={({pressed})=>[s.logout,pressed&&{opacity:.7}]}><Text style={s.logoutText}>ВИЙТИ З АКАУНТА</Text><Text style={s.logoutText}>→</Text></Pressable>
  </ScrollView></Screen>;
}
function ThemeOption({mode,current,title,subtitle,onPress}:{mode:ThemeMode;current:ThemeMode;title:string;subtitle:string;onPress:()=>void}){const active=mode===current;const palette=mode==='dark'?{bg:'#090B10',surface:'#151B24',accent:'#8797C8'}:mode==='light'?{bg:'#F3F5F8',surface:'#FFFFFF',accent:'#586D9E'}:{bg:'#061016',surface:'#0D1B24',accent:'#F28A3D'};return <Pressable onPress={onPress} style={({pressed})=>[s.themePreview,active&&s.themePreviewActive,pressed&&{transform:[{scale:.98}]}]}><View style={[s.previewCanvas,{backgroundColor:palette.bg}]}><View style={[s.miniHeader,{backgroundColor:palette.surface}]}><View style={[s.miniDot,{backgroundColor:palette.accent}]}/><View style={[s.miniDash,{backgroundColor:palette.accent}]}/></View><View style={[s.miniCard,{backgroundColor:palette.surface}]}><View style={[s.miniRoute,{backgroundColor:palette.accent}]}/><View style={[s.miniRouteDot,{backgroundColor:palette.accent}]}/></View><View style={s.miniNav}>{[0,1,2,3].map(i=><View key={i} style={[s.miniNavDot,{backgroundColor:i===0?palette.accent:'#59616D'}]}/>)}</View>{mode==='badger'&&<View style={s.badgerBadge}><BadgerMark size={22}/></View>}{active&&<View style={[s.check,{backgroundColor:palette.accent}]}><Text style={s.checkText}>✓</Text></View>}</View><Text style={[s.segmentText,active&&s.segmentTextActive]}>{title}</Text><Text style={s.previewMeta}>{subtitle}</Text></Pressable>}
function Stat({value,label}:{value:string;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
function MenuRow({icon,title,meta,onPress}:{icon:string;title:string;meta:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.menu,pressed&&{opacity:.72,transform:[{scale:.995}]}]}><View style={s.menuLeft}><View style={s.menuIcon}><Text style={s.menuIconText}>{icon}</Text></View><View><Text style={s.menuTitle}>{title}</Text><Text style={s.menuMeta}>{meta}</Text></View></View><Text style={s.menuArrow}>→</Text></Pressable>}
const s=themedStyleSheet(()=>({
  header:{height:90,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.5},pageTitle:{color:colors.text,fontSize:30,fontWeight:'900',marginTop:3},build:{paddingHorizontal:10,paddingVertical:6,borderRadius:radii.pill,backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.borderStrong},buildText:{color:colors.accent,fontSize:9,fontWeight:'900'},
  hero:{flexDirection:'row',gap:15,alignItems:'center',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:17,elevation:2,shadowColor:colors.shadow,shadowOpacity:.08,shadowRadius:12,shadowOffset:{width:0,height:4}},avatar:{width:64,height:64,borderRadius:20,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.accentText,fontSize:20,fontWeight:'900'},name:{color:colors.text,fontSize:21,fontWeight:'900'},email:{color:colors.textSecondary,fontSize:11,marginTop:3},verifyPill:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:4,borderRadius:radii.pill,backgroundColor:colors.surfaceRaised,flexDirection:'row',alignItems:'center',gap:5},verifyDot:{width:5,height:5,borderRadius:3,backgroundColor:colors.success},verifyText:{color:colors.textSecondary,fontSize:8,fontWeight:'900',letterSpacing:.8},
  stats:{flexDirection:'row',gap:8,marginTop:10},stat:{flex:1,backgroundColor:colors.surfaceRaised,borderRadius:radii.md,paddingVertical:13,alignItems:'center',borderWidth:1,borderColor:colors.border},statValue:{color:colors.text,fontSize:19,fontWeight:'900'},statLabel:{color:colors.muted,fontSize:8,fontWeight:'900',marginTop:3},sectionLabel:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:22,marginBottom:8},
  themeCard:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.lg,padding:15,gap:11},themeTitleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},cardTitle:{color:colors.text,fontSize:15,fontWeight:'900'},themeMeta:{color:colors.muted,fontSize:9,marginTop:3},signature:{flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:7,paddingVertical:5,borderRadius:radii.pill,backgroundColor:colors.accentSoft},signatureText:{color:colors.accent,fontSize:7,fontWeight:'900',letterSpacing:.8},cardText:{color:colors.textSecondary,fontSize:11,lineHeight:17,marginTop:2},themeGrid:{flexDirection:'row',gap:8,marginTop:3},themePreview:{flex:1,minHeight:135,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,padding:7,backgroundColor:colors.surfaceMuted},themePreviewActive:{borderColor:colors.accent,backgroundColor:colors.accentSoft},previewCanvas:{height:82,borderRadius:10,overflow:'hidden',padding:7,marginBottom:8,borderWidth:1,borderColor:'rgba(130,145,165,.16)'},miniHeader:{height:9,borderRadius:4,marginBottom:6,flexDirection:'row',alignItems:'center',paddingHorizontal:4,gap:3},miniDot:{width:3,height:3,borderRadius:2},miniDash:{height:2,width:18,borderRadius:2},miniCard:{height:37,borderRadius:6,position:'relative',overflow:'hidden'},miniRoute:{position:'absolute',left:7,right:7,top:18,height:2,borderRadius:2,transform:[{rotate:'-12deg'}]},miniRouteDot:{position:'absolute',right:10,top:10,width:6,height:6,borderRadius:3},miniNav:{position:'absolute',left:8,right:8,bottom:6,height:9,borderRadius:5,backgroundColor:'rgba(15,20,28,.55)',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},miniNavDot:{width:3,height:3,borderRadius:2},badgerBadge:{position:'absolute',left:9,bottom:14},check:{position:'absolute',right:7,top:7,width:17,height:17,borderRadius:9,alignItems:'center',justifyContent:'center'},checkText:{color:'#071018',fontSize:10,fontWeight:'900'},segmentText:{color:colors.textSecondary,fontSize:8,fontWeight:'900',textAlign:'center'},segmentTextActive:{color:colors.accent},previewMeta:{color:colors.muted,fontSize:6,fontWeight:'900',letterSpacing:.8,textAlign:'center',marginTop:2},
  menu:{minHeight:70,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,paddingHorizontal:14,marginBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},menuLeft:{flexDirection:'row',alignItems:'center',gap:12},menuIcon:{width:34,height:34,borderRadius:10,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},menuIconText:{color:colors.accent,fontSize:10,fontWeight:'900'},menuTitle:{color:colors.text,fontSize:13,fontWeight:'900'},menuMeta:{color:colors.muted,fontSize:9,marginTop:4},menuArrow:{color:colors.accent,fontSize:18,fontWeight:'900'},info:{borderRadius:radii.md,backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.borderStrong,padding:14,marginTop:6},infoHead:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:2},infoTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.2},logout:{minHeight:54,borderRadius:radii.md,borderWidth:1,borderColor:colors.danger,paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:14},logoutText:{color:colors.danger,fontSize:10,fontWeight:'900',letterSpacing:.8},
}));
