import {router} from 'expo-router';
import {useEffect,useMemo,useState} from 'react';
import {Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {apiFetch,readJsonSafe} from '@/api/client';
import {Screen} from '@/ui/screen';
import {BadgerMark} from '@/ui/badger-mark';
import {FadeInView, PulseDot} from '@/ui/motion';
import {BrandIcon} from '@/ui/brand-icons';
import {colors,radii,themedStyleSheet} from '@/theme/tokens';

type P={mode:'casual'|'professional';professionalStatus:string;professionalNote?:string|null;businessName?:string|null;businessRegistrationRef?:string|null;acceptedCasualPolicyAt?:string|null;policy:{maxFutureTrips:number;maxTrips30d:number;maxCompletedDeliveries30d:number;maxDetourKm:number}};

type Tone={label:string;color:string;soft:string;description:string};
function professionalTone(status?:string):Tone{switch(status){case'verified':return{label:'VERIFIED BUSINESS',color:colors.success,soft:colors.successSoft,description:'Профіль підтверджено. Професійні маршрути та пропозиції доступні.'};case'pending':return{label:'UNDER REVIEW',color:colors.warning,soft:colors.warningSoft,description:'Реквізити на перевірці. До підтвердження професійні операції заблоковані.'};case'rejected':return{label:'ACTION REQUIRED',color:colors.danger,soft:colors.dangerSoft,description:'Профіль потребує виправлення реквізитів і повторної перевірки.'};default:return{label:'NOT ACTIVATED',color:colors.muted,soft:colors.surfaceRaised,description:'Заповніть реквізити, щоб активувати професійний профіль.'}}}

export default function CarrierMode(){
 const[p,setP]=useState<P|null>(null);const[mode,setMode]=useState<'casual'|'professional'>('casual');const[name,setName]=useState('');const[reg,setReg]=useState('');const[accepted,setAccepted]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');
 async function load(){const r=await apiFetch('/carrier-mode/me');const d=await readJsonSafe<P>(r);if(!r.ok||!d)throw new Error((d as any)?.message??'Не вдалося завантажити профіль');setP(d);setMode(d.mode);setName(d.businessName??'');setReg(d.businessRegistrationRef??'');setAccepted(!!d.acceptedCasualPolicyAt)}
 useEffect(()=>{void load().catch(e=>setErr(e.message))},[]);
 async function save(){setBusy(true);setErr('');try{const r=await apiFetch('/carrier-mode/me',{method:'PATCH',body:JSON.stringify(mode==='casual'?{mode,acceptCasualPolicy:accepted}:{mode,businessName:name,businessRegistrationRef:reg})});const d=await readJsonSafe<P>(r);if(!r.ok||!d)throw new Error((d as any)?.message??'Не вдалося зберегти');setP(d);router.back()}catch(e){setErr(e instanceof Error?e.message:'Помилка')}finally{setBusy(false)}}
 const tone=useMemo(()=>professionalTone(p?.professionalStatus),[p?.professionalStatus]);
 return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:40}}>
  <View style={s.head}><Pressable onPress={()=>router.back()} hitSlop={12} style={s.backButton}><Text style={s.back}>←</Text></Pressable><View style={{flex:1}}><Text style={s.eye}>CARRIER IDENTITY</Text><Text style={s.title}>Режим перевізника</Text></View><View style={s.brandMini}><BadgerMark size={31}/></View></View>
  <Text style={s.intro}>Оберіть формат роботи. Для попутних поїздок діють anti-commercial ліміти; ФОП отримує окремий професійний простір без casual-обмежень.</Text>
  <View style={s.row}><Mode active={mode==='casual'} title="ПОПУТНИК" sub="PERSONAL" icon="route" onPress={()=>setMode('casual')}/><Mode active={mode==='professional'} title="CARGOGO PRO" sub="ФОП / BUSINESS" icon="deals" onPress={()=>setMode('professional')}/></View>
  {mode==='casual'?<Casual p={p} accepted={accepted} setAccepted={setAccepted}/>:<Professional p={p} name={name} setName={setName} reg={reg} setReg={setReg} tone={tone}/>} 
  {!!err&&<Text style={s.err}>{err}</Text>}
  <Pressable disabled={busy||(mode==='casual'&&!accepted)} onPress={save} style={({pressed})=>[s.primary,(busy||(mode==='casual'&&!accepted))&&{opacity:.45},pressed&&{transform:[{scale:.992}]}]}><View><Text style={s.primaryOver}>{mode==='professional'?'BUSINESS PROFILE':'CARRIER PROFILE'}</Text><Text style={s.primaryText}>{busy?'ЗБЕРІГАЄМО...':mode==='professional'?'ЗБЕРЕГТИ ПРОФІЛЬ':'ЗБЕРЕГТИ РЕЖИМ'}</Text></View><Text style={s.primaryArrow}>→</Text></Pressable>
 </ScrollView></Screen>
}

function Casual({p,accepted,setAccepted}:{p:P|null;accepted:boolean;setAccepted:(v:boolean)=>void}){return <FadeInView><View style={s.card}><Text style={s.cardKicker}>PERSONAL · COST SHARING</Text><Text style={s.cardTitle}>Попутна поїздка, а не бізнес</Text><Text style={s.text}>Маршрут планується вами незалежно від вантажу. CargoGo контролює частоту та компенсацію, щоб режим не перетворювався на систематичну комерційну діяльність.</Text><View style={s.rules}><Rule value={String(p?.policy.maxFutureTrips??2)} label="активні поїздки"/><Rule value={String(p?.policy.maxTrips30d??8)} label="поїздок / 30 днів"/><Rule value={`${p?.policy.maxDetourKm??30} км`} label="макс. відхилення"/></View><Text style={s.smallRule}>До {p?.policy.maxCompletedDeliveries30d??12} завершених доставок за 30 днів · компенсація не вище розрахункового ліміту витрат.</Text><Pressable onPress={()=>router.push({pathname:'/legal/[key]' as any,params:{key:'casual-carrier-policy'}})} style={s.policyLink}><Text style={s.policyLinkText}>ПРОЧИТАТИ ПОВНІ CASUAL DRIVER RULES</Text><Text style={s.policyLinkText}>→</Text></Pressable><Pressable onPress={()=>setAccepted(!accepted)} style={[s.accept,accepted&&s.acceptOn]}><Text style={s.check}>{accepted?'✓':'○'}</Text><Text style={s.acceptText}>Підтверджую, що використовую CargoGo для власних попутних поїздок, а не регулярного заробітку.</Text></Pressable></View></FadeInView>}

function Professional({p,name,setName,reg,setReg,tone}:{p:P|null;name:string;setName:(x:string)=>void;reg:string;setReg:(x:string)=>void;tone:Tone}){const verified=p?.professionalStatus==='verified';return <View>
 <FadeInView><View style={s.proHero}><View style={s.proTop}><View><Text style={s.proOverline}>CARGOGO PRO</Text><Text style={s.proTitle}>Business Carrier</Text><Text style={s.proSubtitle}>Професійний профіль перевізника</Text></View><View style={s.proMark}><BadgerMark size={48}/></View></View><View style={[s.statusBar,{backgroundColor:tone.soft,borderColor:tone.color}]}><View style={s.statusLeft}>{verified?<PulseDot color={tone.color} size={7}/>:<View style={[s.staticDot,{backgroundColor:tone.color}]}/>}<View><Text style={[s.statusLabel,{color:tone.color}]}>{tone.label}</Text><Text style={s.statusDescription}>{tone.description}</Text></View></View></View><View style={s.proMetrics}><ProMetric value="∞" label="CASUAL LIMITS" sub="не застосовуються"/><ProMetric value={verified?'ON':'LOCK'} label="OPERATIONS" sub={verified?'business ready':'до перевірки'}/><ProMetric value="PRO" label="ACCOUNT" sub="проф. режим"/></View></View></FadeInView>
 <FadeInView delay={45}><View style={s.businessCard}><View style={s.sectionHead}><View><Text style={s.sectionEye}>LEGAL IDENTITY</Text><Text style={s.sectionTitle}>Реквізити перевізника</Text></View><View style={s.secureBadge}><BrandIcon name="deals" color={colors.accent} size={16}/><Text style={s.secureText}>SECURE</Text></View></View><Field label="НАЗВА / ПІБ ФОП" value={name} setValue={setName} placeholder="ФОП Іваненко Іван Іванович"/><Field label="РНОКПП / ЄДРПОУ" value={reg} setValue={setReg} placeholder="Реєстраційний ідентифікатор" keyboardType="number-pad"/><View style={s.auditLine}><View style={s.auditIcon}><Text style={s.auditIconText}>↻</Text></View><Text style={s.auditText}>Зміна реквізитів автоматично повертає профіль на ручну перевірку. Старі угоди зберігають snapshot попереднього статусу.</Text></View>{p?.professionalStatus==='rejected'&&!!p.professionalNote&&<View style={s.reviewNote}><Text style={s.reviewNoteTitle}>КОМЕНТАР REVIEWER</Text><Text style={s.reviewNoteText}>{p.professionalNote}</Text></View>}</View></FadeInView>
 <FadeInView delay={80}><View style={s.toolCard}><Text style={s.sectionEye}>PRO WORKSPACE</Text><Text style={s.sectionTitle}>Робочі інструменти</Text><View style={s.actionGrid}><ProAction icon="₴" title="Виплати" meta="IBAN · payout" onPress={()=>router.push('/payout-settings')}/><ProAction icon="↗" title="Маршрути" meta="керування" onPress={()=>router.push('/(tabs)')}/><ProAction icon="＋" title="Нова поїздка" meta="створити" onPress={()=>router.push('/create-trip')}/><ProAction icon="◎" title="Угоди" meta="активні" onPress={()=>router.push('/(tabs)/deals')}/></View></View></FadeInView>
 <View style={s.proNotice}><Text style={s.proNoticeTitle}>ПРОФЕСІЙНИЙ РЕЖИМ</Text><Text style={s.proNoticeText}>Для ФОП не діють casual-ліміти частоти, відхилення та компенсації. Верифікація особи, прав, авто і бізнес-профілю залишається обов’язковою.</Text></View>
 </View>}

function Field({label,value,setValue,placeholder,keyboardType}:{label:string;value:string;setValue:(x:string)=>void;placeholder:string;keyboardType?:'default'|'number-pad'}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={setValue} style={s.input} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType??'default'} selectionColor={colors.accent}/></View>}
function Rule({value,label}:{value:string;label:string}){return <View style={s.ruleBox}><Text style={s.ruleValue}>{value}</Text><Text style={s.ruleLabel}>{label}</Text></View>}
function ProMetric({value,label,sub}:{value:string;label:string;sub:string}){return <View style={s.proMetric}><Text style={s.proMetricValue}>{value}</Text><Text style={s.proMetricLabel}>{label}</Text><Text style={s.proMetricSub}>{sub}</Text></View>}
function ProAction({icon,title,meta,onPress}:{icon:string;title:string;meta:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.proAction,pressed&&{opacity:.72,transform:[{scale:.985}]}]}><View style={s.proActionIcon}><Text style={s.proActionIconText}>{icon}</Text></View><Text style={s.proActionTitle}>{title}</Text><Text style={s.proActionMeta}>{meta}</Text></Pressable>}
function Mode({active,title,sub,icon,onPress}:{active:boolean;title:string;sub:string;icon:'route'|'deals';onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.mode,active&&s.modeOn,pressed&&{transform:[{scale:.985}]}]}><View style={s.modeHead}><View style={[s.modeIcon,active&&s.modeIconOn]}><BrandIcon name={icon} color={active?colors.accent:colors.muted} size={17}/></View><Text style={s.modeMark}>{active?'●':'○'}</Text></View><Text style={[s.modeTitle,active&&{color:colors.accent}]}>{title}</Text><Text style={s.modeSub}>{sub}</Text></Pressable>}

const s=themedStyleSheet(()=>({
 head:{minHeight:94,flexDirection:'row',alignItems:'center',gap:12},backButton:{width:36,height:36,borderRadius:12,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},back:{color:colors.text,fontSize:21,fontWeight:'900',marginTop:-2},brandMini:{width:44,height:44,borderRadius:14,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},eye:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.8},title:{color:colors.text,fontSize:25,fontWeight:'900',marginTop:3,letterSpacing:-.4},intro:{color:colors.textSecondary,fontSize:11,lineHeight:18,marginBottom:16},row:{flexDirection:'row',gap:9},mode:{flex:1,minHeight:118,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,padding:13},modeOn:{borderColor:colors.accent,backgroundColor:colors.accentSoft},modeHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modeIcon:{width:34,height:34,borderRadius:11,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceRaised,alignItems:'center',justifyContent:'center'},modeIconOn:{borderColor:colors.borderStrong,backgroundColor:colors.surface},modeTitle:{color:colors.text,fontSize:11,fontWeight:'900',marginTop:12,letterSpacing:.4},modeSub:{color:colors.muted,fontSize:8,fontWeight:'800',marginTop:4,letterSpacing:.7},modeMark:{color:colors.accent,fontSize:13},
 card:{marginTop:11,borderRadius:radii.xl,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.surface,padding:18},cardKicker:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.4},cardTitle:{color:colors.text,fontSize:18,fontWeight:'900',marginTop:5},text:{color:colors.textSecondary,fontSize:11,lineHeight:18,marginTop:8},rules:{flexDirection:'row',gap:7,marginTop:15},ruleBox:{flex:1,minHeight:76,borderRadius:radii.md,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border,padding:10,justifyContent:'center'},ruleValue:{color:colors.text,fontSize:18,fontWeight:'900'},ruleLabel:{color:colors.muted,fontSize:7,lineHeight:11,fontWeight:'800',marginTop:4,textTransform:'uppercase'},smallRule:{color:colors.muted,fontSize:9,lineHeight:15,marginTop:11},policyLink:{marginTop:12,minHeight:43,borderWidth:1,borderColor:colors.borderStrong,borderRadius:radii.md,paddingHorizontal:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.surfaceRaised},policyLinkText:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:.7},accept:{marginTop:14,borderWidth:1,borderColor:colors.border,padding:13,borderRadius:radii.md,flexDirection:'row',alignItems:'flex-start',gap:10},acceptOn:{borderColor:colors.accent,backgroundColor:colors.accentSoft},check:{color:colors.accent,fontSize:17,fontWeight:'900'},acceptText:{flex:1,color:colors.text,fontSize:10,lineHeight:16},
 proHero:{marginTop:11,borderRadius:24,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.surface,padding:18,overflow:'hidden'},proTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},proOverline:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:2},proTitle:{color:colors.text,fontSize:27,fontWeight:'900',letterSpacing:-.8,marginTop:4},proSubtitle:{color:colors.textSecondary,fontSize:10,marginTop:3},proMark:{width:62,height:62,borderRadius:19,backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.borderStrong,alignItems:'center',justifyContent:'center'},statusBar:{marginTop:16,borderRadius:radii.md,borderWidth:1,padding:11},statusLeft:{flexDirection:'row',alignItems:'center',gap:9},staticDot:{width:7,height:7,borderRadius:4},statusLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2},statusDescription:{color:colors.textSecondary,fontSize:8,lineHeight:13,marginTop:2,maxWidth:265},proMetrics:{flexDirection:'row',gap:7,marginTop:12},proMetric:{flex:1,minHeight:83,borderRadius:radii.md,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border,padding:10},proMetricValue:{color:colors.text,fontSize:19,fontWeight:'900'},proMetricLabel:{color:colors.accent,fontSize:6,fontWeight:'900',letterSpacing:.8,marginTop:5},proMetricSub:{color:colors.muted,fontSize:7,marginTop:3},
 businessCard:{marginTop:10,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,padding:16},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},sectionEye:{color:colors.accent,fontSize:7,fontWeight:'900',letterSpacing:1.5},sectionTitle:{color:colors.text,fontSize:16,fontWeight:'900',marginTop:3},secureBadge:{flexDirection:'row',alignItems:'center',gap:5,borderWidth:1,borderColor:colors.border,paddingHorizontal:8,paddingVertical:6,borderRadius:radii.pill,backgroundColor:colors.surfaceRaised},secureText:{color:colors.muted,fontSize:6,fontWeight:'900',letterSpacing:.8},field:{marginTop:14},label:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:.9,marginBottom:6},input:{height:52,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.background,color:colors.text,paddingHorizontal:13,borderRadius:radii.md,fontSize:12,fontWeight:'700'},auditLine:{marginTop:12,flexDirection:'row',alignItems:'flex-start',gap:9,padding:11,borderRadius:radii.md,backgroundColor:colors.surfaceRaised},auditIcon:{width:24,height:24,borderRadius:8,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},auditIconText:{color:colors.accent,fontSize:12,fontWeight:'900'},auditText:{flex:1,color:colors.muted,fontSize:8,lineHeight:13},reviewNote:{marginTop:12,borderWidth:1,borderColor:colors.danger,backgroundColor:colors.dangerSoft,borderRadius:radii.md,padding:11},reviewNoteTitle:{color:colors.danger,fontSize:7,fontWeight:'900',letterSpacing:1},reviewNoteText:{color:colors.textSecondary,fontSize:9,lineHeight:14,marginTop:4},
 toolCard:{marginTop:10,borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,padding:16},actionGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:13},proAction:{width:'48%',minHeight:104,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceRaised,padding:12},proActionIcon:{width:30,height:30,borderRadius:10,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},proActionIconText:{color:colors.accent,fontSize:13,fontWeight:'900'},proActionTitle:{color:colors.text,fontSize:11,fontWeight:'900',marginTop:10},proActionMeta:{color:colors.muted,fontSize:8,marginTop:3},proNotice:{marginTop:10,borderRadius:radii.md,borderLeftWidth:3,borderLeftColor:colors.accent,backgroundColor:colors.surfaceMuted,padding:13},proNoticeTitle:{color:colors.accent,fontSize:7,fontWeight:'900',letterSpacing:1.2},proNoticeText:{color:colors.textSecondary,fontSize:9,lineHeight:15,marginTop:4},
 err:{color:colors.danger,fontSize:10,marginTop:10},primary:{minHeight:60,borderRadius:radii.lg,backgroundColor:colors.accent,marginTop:12,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},primaryOver:{color:colors.accentText,fontSize:6,fontWeight:'900',letterSpacing:1.3,opacity:.7},primaryText:{color:colors.accentText,fontSize:11,fontWeight:'900',marginTop:2},primaryArrow:{color:colors.accentText,fontSize:22,fontWeight:'900'}
}));
