import {router,useFocusEffect} from 'expo-router';
import {useCallback,useState} from 'react';
import {Pressable,ScrollView,Text,View} from 'react-native';
import {Screen} from '@/ui/screen';
import {BadgerMark} from '@/ui/badger-mark';
import {colors,radii,themedStyleSheet} from '@/theme/tokens';
import {loadDriverReadiness,type DriverReadiness} from '@/readiness/driver-readiness';

export default function DriverReadinessScreen(){
 const[data,setData]=useState<DriverReadiness|null>(null);const[err,setErr]=useState('');
 const load=useCallback(()=>{setErr('');void loadDriverReadiness().then(setData).catch(e=>setErr(e instanceof Error?e.message:'Помилка'))},[]);
 useFocusEffect(load);
 return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:36}}>
  <View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>←</Text></Pressable><View style={{flex:1}}><Text style={s.eye}>DRIVER READINESS</Text><Text style={s.title}>Готовність до перевезень</Text></View><BadgerMark size={38}/></View>
  <Text style={s.intro}>CargoGo перевіряє необхідні умови до того, як ви витратите час на заповнення маршруту. Після виконання всіх кроків створення поїздок стане доступним.</Text>
  <View style={s.progress}><View><Text style={s.progressEye}>ГОТОВНІСТЬ</Text><Text style={s.progressValue}>{data?`${data.completed}/${data.total}`:'—'}</Text></View><Text style={[s.progressState,data?.ready&&{color:colors.success}]}>{data?.ready?'МОЖНА ЇХАТИ':'ПОТРІБНА ДІЯ'}</Text></View>
  <Step done={!!data?.identityReady} title="Підтвердження особи" text={data?.identityReady?'Особу підтверджено.':'Завантажте документ та дочекайтеся підтвердження reviewer.'} action="ВЕРИФІКАЦІЯ" onPress={()=>router.push('/verification')}/>
  <Step done={!!(data?.licenseReady&&data?.vehicleReady)} title="Водій і автомобіль" text={data?.licenseReady&&data?.vehicleReady?'Посвідчення та щонайменше один автомобіль підтверджені.':`${data?.licenseReady?'Посвідчення ✓':'Потрібне посвідчення'} · ${data?.vehicleReady?'Авто ✓':'Потрібне підтверджене авто'}`} action="ВІДКРИТИ ЦЕНТР" onPress={()=>router.push('/verification')}/>
  <Step done={!!data?.carrierReady} title="Режим перевізника та правила" text={data?.carrier.mode==='professional'?(data?.carrierReady?'Професійний профіль підтверджено.':'Професійний профіль має пройти перевірку.'):(data?.carrierReady?'Правила попутного режиму прийнято.':'Оберіть попутний або професійний режим і прийміть відповідні умови.')} action="НАЛАШТУВАТИ" onPress={()=>router.push('/carrier-mode')}/>
  {!!err&&<Text style={s.err}>{err}</Text>}
  {data?.ready?<Pressable onPress={()=>router.replace('/create-trip')} style={s.primary}><View><Text style={s.primaryOver}>ALL CHECKS PASSED</Text><Text style={s.primaryText}>СТВОРИТИ ПОЇЗДКУ</Text></View><Text style={s.primaryText}>→</Text></Pressable>:<View style={s.note}><Text style={s.noteTitle}>ЧОМУ ЦЕ ДО ПОЇЗДКИ</Text><Text style={s.noteText}>Backend все одно блокує поїздку без цих умов. Цей екран показує вимоги заздалегідь, щоб ви не заповнювали маршрут даремно.</Text></View>}
 </ScrollView></Screen>
}
function Step({done,title,text,action,onPress}:{done:boolean;title:string;text:string;action:string;onPress:()=>void}){return <View style={[s.step,done&&s.stepDone]}><View style={s.stepTop}><View style={[s.icon,done&&s.iconDone]}><Text style={[s.iconText,done&&{color:colors.success}]}>{done?'✓':'!'}</Text></View><View style={{flex:1}}><Text style={s.stepTitle}>{title}</Text><Text style={s.stepText}>{text}</Text></View></View>{!done&&<Pressable onPress={onPress} style={s.stepAction}><Text style={s.stepActionText}>{action}</Text><Text style={s.stepActionText}>→</Text></Pressable>}</View>}
const s=themedStyleSheet(()=>({head:{minHeight:96,flexDirection:'row',alignItems:'center',gap:12},back:{width:38,height:38,borderRadius:12,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},backText:{color:colors.text,fontSize:20,fontWeight:'900'},eye:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:23,fontWeight:'900',marginTop:3},intro:{color:colors.textSecondary,fontSize:11,lineHeight:18,marginBottom:13},progress:{borderRadius:radii.lg,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.surface,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:9},progressEye:{color:colors.muted,fontSize:7,fontWeight:'900',letterSpacing:1.3},progressValue:{color:colors.text,fontSize:27,fontWeight:'900',marginTop:3},progressState:{color:colors.warning,fontSize:8,fontWeight:'900',letterSpacing:1},step:{borderRadius:radii.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,padding:14,marginBottom:8},stepDone:{backgroundColor:colors.surfaceRaised},stepTop:{flexDirection:'row',gap:11,alignItems:'flex-start'},icon:{width:32,height:32,borderRadius:10,backgroundColor:colors.warningSoft,alignItems:'center',justifyContent:'center'},iconDone:{backgroundColor:colors.successSoft},iconText:{color:colors.warning,fontSize:15,fontWeight:'900'},stepTitle:{color:colors.text,fontSize:13,fontWeight:'900'},stepText:{color:colors.textSecondary,fontSize:10,lineHeight:16,marginTop:3},stepAction:{minHeight:42,borderTopWidth:1,borderTopColor:colors.border,marginTop:12,paddingTop:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},stepActionText:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:.6},err:{color:colors.danger,fontSize:10,marginVertical:8},primary:{minHeight:60,borderRadius:radii.lg,backgroundColor:colors.accent,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:5},primaryOver:{color:colors.accentText,fontSize:6,fontWeight:'900',letterSpacing:1.2,opacity:.7},primaryText:{color:colors.accentText,fontSize:11,fontWeight:'900',marginTop:2},note:{marginTop:6,borderLeftWidth:2,borderLeftColor:colors.accent,backgroundColor:colors.surfaceRaised,padding:13},noteTitle:{color:colors.accent,fontSize:8,fontWeight:'900',letterSpacing:1},noteText:{color:colors.textSecondary,fontSize:10,lineHeight:16,marginTop:5}}));
