import { Redirect, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { apiFetch, readJsonSafe } from '@/api/client';
import { useAuth } from '@/auth/auth-context';
import { colors, radii, themedStyleSheet } from '@/theme/tokens';
import { Screen } from '@/ui/screen';
import {useLiveVersion} from '@/live/live-context';

type Item={id:string;dealId:string;status:string;amountMinor:number;currency:string;provider:string;attempts:number;lastError:string|null;createdAt:string;updatedAt:string;settlementStatus:string;paymentStatus:string;driverName:string;driverPhone:string|null};
export default function PayoutReview(){const live=useLiveVersion('staff','deals');const{user}=useAuth();const[items,setItems]=useState<Item[]>([]);const[err,setErr]=useState('');const load=useCallback(async()=>{const r=await apiFetch('/staff/payout-issues');const x=await readJsonSafe<any>(r);if(r.ok){setItems(Array.isArray(x)?x:[]);setErr('')}else setErr(x?.message??'Немає доступу')},[]);useFocusEffect(useCallback(()=>{void load()},[load,live]));if(!user)return <Redirect href="/auth"/>;if(!user.staffRole)return <Redirect href="/(tabs)"/>;return <Screen><ScrollView contentContainerStyle={{paddingBottom:60}}><View style={s.head}><Pressable onPress={()=>router.replace('/staff')}><Text style={s.back}>←</Text></Pressable><View><Text style={s.eye}>OPERATIONS · FINANCE</Text><Text style={s.title}>Проблемні виплати</Text></View></View><View style={s.notice}><Text style={s.noticeTitle}>БЕЗПЕЧНИЙ РЕЖИМ</Text><Text style={s.noticeBody}>Ця черга поки тільки для діагностики. Reviewer не може вручну змінити баланс, поставити payout у PAID або виконати refund. Такі дії додамо тільки через окремий idempotent provider workflow.</Text></View>{!!err&&<Text style={s.err}>{err}</Text>}{items.map(x=><View key={x.id} style={s.card}><View style={s.row}><Text style={s.name}>{x.driverName}</Text><Text style={s.badge}>{x.status.toUpperCase()}</Text></View><Text style={s.amount}>{(x.amountMinor/100).toFixed(2)} {x.currency==='UAH'?'₴':x.currency}</Text><Text style={s.meta}>DEAL {x.dealId.slice(0,8)}… · {x.provider}</Text><Text style={s.meta}>SETTLEMENT {x.settlementStatus} · PAYMENT {x.paymentStatus}</Text><Text style={s.meta}>Спроб: {x.attempts} · {new Date(x.updatedAt).toLocaleString()}</Text>{!!x.lastError&&<Text style={s.errorText}>{x.lastError}</Text>}</View>)}{!items.length&&!err&&<Text style={s.empty}>Проблемних виплат немає.</Text>}</ScrollView></Screen>}
const s=themedStyleSheet(()=>({head:{minHeight:95,flexDirection:'row',alignItems:'center',gap:14},back:{color:colors.text,fontSize:26,fontWeight:'900'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.2},title:{color:colors.text,fontSize:25,fontWeight:'900',marginTop:3},notice:{backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.accent,borderRadius:radii.lg,padding:14,marginBottom:12},noticeTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.1},noticeBody:{color:colors.textSecondary,fontSize:10,lineHeight:16,marginTop:6},err:{color:colors.danger,fontWeight:'800',marginBottom:10},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:15,marginBottom:9},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},name:{color:colors.text,fontSize:15,fontWeight:'900'},badge:{color:colors.danger,fontSize:8,fontWeight:'900'},amount:{color:colors.text,fontSize:22,fontWeight:'900',marginTop:10},meta:{color:colors.muted,fontSize:9,marginTop:5},errorText:{color:colors.danger,fontSize:10,lineHeight:15,marginTop:8},empty:{color:colors.muted,marginTop:20}}));
