import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiFetch } from '@/api/client';
import type { PayoutAccount } from '@/api/types';
import {colors,themedStyleSheet} from '@/theme/tokens';
import { Screen } from '@/ui/screen';

export default function PayoutSettings(){
  const[account,setAccount]=useState<PayoutAccount|null>(null);const[holderName,setHolderName]=useState('');const[iban,setIban]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{try{const r=await apiFetch('/payout-accounts/me');if(r.ok)setAccount(await r.json())}catch{}},[]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  async function save(){setBusy(true);setError('');setNotice('');try{const r=await apiFetch('/payout-accounts/me',{method:'POST',body:JSON.stringify({holderName:holderName.trim(),iban:iban.replace(/\s+/g,'').toUpperCase()})});const d=await r.json();if(!r.ok)throw new Error(d?.message??d?.error?.message??d?.issues?.[0]?.message??'Не вдалося зберегти реквізити');setAccount(d);setIban('');setNotice('Реквізити для виплат збережено у зашифрованому вигляді.')}catch(e){setError(e instanceof Error?e.message:'Помилка')}finally{setBusy(false)}}
  async function disable(){setBusy(true);setError('');try{const r=await apiFetch('/payout-accounts/me',{method:'DELETE'});if(!r.ok){const d=await r.json();throw new Error(d?.message??'Не вдалося видалити')}setAccount(null);setNotice('Реквізити вимкнено.')}catch(e){setError(e instanceof Error?e.message:'Помилка')}finally{setBusy(false)}}
  return <Screen><ScrollView contentContainerStyle={{paddingBottom:32}}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>←</Text></Pressable><View><Text style={s.eye}>ФІНАНСИ</Text><Text style={s.title}>Оплата і виплати</Text></View></View>
    <View style={s.info}><Text style={s.infoTitle}>ОПЛАТА КЛІЄНТА</Text><Text style={s.infoText}>Картка вводиться тільки на захищеній сторінці платіжного провайдера. CargoGo не зберігає номер картки або CVV. Після прийняття перевізника клієнт підтверджує HOLD на повну суму угоди.</Text></View>
    <View style={s.panel}><Text style={s.eye}>ВИПЛАТА ПЕРЕВІЗНИКУ</Text><Text style={s.panelTitle}>{account?'Реквізити налаштовані':'Додайте IBAN'}</Text>{account&&<><Text style={s.mask}>{account.maskedIban}</Text><Text style={s.meta}>UAH · {account.status.toUpperCase()}</Text></>}
      <Text style={s.label}>ПІБ ОДЕРЖУВАЧА</Text><TextInput value={holderName} onChangeText={setHolderName} placeholder="Іван Іваненко" placeholderTextColor={colors.muted} style={s.input}/>
      <Text style={s.label}>IBAN</Text><TextInput value={iban} onChangeText={v=>setIban(v.toUpperCase().replace(/\s/g,'').slice(0,29))} autoCapitalize="characters" placeholder="UA123456789012345678901234567" placeholderTextColor={colors.muted} style={s.input}/>
      {!!error&&<Text style={s.error}>{error}</Text>}{!!notice&&<Text style={s.success}>{notice}</Text>}
      <Pressable disabled={busy||holderName.trim().length<3||iban.length!==29} onPress={save} style={[s.primary,(busy||holderName.trim().length<3||iban.length!==29)&&{opacity:.5}]}><Text style={s.primaryText}>{account?'ОНОВИТИ РЕКВІЗИТИ':'ЗБЕРЕГТИ РЕКВІЗИТИ'}</Text><Text style={s.primaryText}>→</Text></Pressable>
      {account&&<Pressable disabled={busy} onPress={disable} style={s.danger}><Text style={s.dangerText}>ВИМКНУТИ РЕКВІЗИТИ</Text></Pressable>}
    </View>
    <View style={s.info}><Text style={s.infoTitle}>ЯК ІДУТЬ ГРОШІ</Text><Text style={s.infoText}>Наприклад 1000 ₴: сума блокується у клієнта → після коду доставки списується → комісія CargoGo фіксується окремо → залишок автоматично створюється як виплата перевізнику. У sandbox виплата симулюється, у production потрібен підключений провайдер payout.</Text></View>
  </ScrollView></Screen>
}
const s=themedStyleSheet(()=>({header:{minHeight:84,flexDirection:'row',alignItems:'center',gap:15,borderBottomWidth:1,borderBottomColor:colors.border},back:{width:40,height:40,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},backText:{color:colors.text,fontSize:20,fontWeight:'900'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{color:colors.text,fontSize:22,fontWeight:'900',marginTop:4},info:{borderLeftWidth:2,borderLeftColor:colors.accent,backgroundColor:colors.surfaceRaised,padding:14,marginTop:16},infoTitle:{color:colors.text,fontSize:10,fontWeight:'900',letterSpacing:1.1},infoText:{color:colors.textSecondary,fontSize:12,lineHeight:19,marginTop:7},panel:{padding:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,marginTop:16},panelTitle:{color:colors.text,fontSize:18,fontWeight:'900',marginTop:5},mask:{color:colors.accent,fontSize:18,fontWeight:'900',marginTop:12},meta:{color:colors.textSecondary,fontSize:10,marginTop:4},label:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.1,marginTop:14},input:{height:50,borderWidth:1,borderColor:colors.border,color:colors.text,paddingHorizontal:12,marginTop:7},primary:{minHeight:52,backgroundColor:colors.accent,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,marginTop:16},primaryText:{color:colors.accentText,fontSize:10,fontWeight:'900'},danger:{height:46,borderWidth:1,borderColor:colors.danger,alignItems:'center',justifyContent:'center',marginTop:10},dangerText:{color:colors.danger,fontSize:10,fontWeight:'900'},error:{color:colors.danger,fontSize:12,marginTop:10},success:{color:colors.success,fontSize:12,marginTop:10}}));
