import { Redirect, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { apiFetch, readJsonSafe } from '@/api/client';
import { useAuth } from '@/auth/auth-context';
import { useAppTheme } from '@/theme/theme-context';
import { colors, radii, themedStyleSheet } from '@/theme/tokens';
import { Screen } from '@/ui/screen';
import {useLiveVersion} from '@/live/live-context';

type Overview={role:string;capabilities:{verification:boolean;professionalCarriers:boolean;disputes:boolean;payoutIssues:boolean;finance:boolean;readiness:boolean;privacy:boolean};counts:{verification:number;professionalCarriers:number;disputes:number;payoutIssues:number;privacy:number}};

export default function StaffHome(){const live=useLiveVersion('staff','notifications');
  const {user,logout}=useAuth(); const {mode,setMode}=useAppTheme(); const [data,setData]=useState<Overview|null>(null); const [err,setErr]=useState('');
  const load=useCallback(async()=>{const r=await apiFetch('/staff/overview');const x=await readJsonSafe<any>(r);if(r.ok){setData(x);setErr('')}else setErr(x?.message??'Немає доступу до staff workspace')},[]);
  useFocusEffect(useCallback(()=>{if(user?.staffRole)void load()},[load,user?.staffRole,live]));
  if(!user)return <Redirect href="/auth"/>; if(!user.staffRole)return <Redirect href="/(tabs)"/>;
  const signOut=async()=>{await logout();router.replace('/auth')};
  return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:50}}>
    <View style={s.head}><View><Text style={s.eye}>CARGOGO · OPERATIONS</Text><Text style={s.title}>Trust Workspace</Text><Text style={s.subtitle}>{user.displayName} · {String(user.staffRole).toUpperCase()}</Text></View><View style={s.staffPill}><Text style={s.staffPillText}>STAFF</Text></View></View>
    {!!err&&<Text style={s.err}>{err}</Text>}
    <View style={s.hero}><Text style={s.heroEye}>РОБОЧА ЗМІНА</Text><Text style={s.heroTitle}>Тільки те, що потребує рішення людини.</Text><Text style={s.heroBody}>Верифікації, ФОП-профілі, спори та проблемні виплати відокремлені від звичайного маркетплейсу. Тут немає створення вантажів, маршрутів чи користувацьких чатів.</Text></View>
    <Text style={s.section}>ЧЕРГИ</Text>
    {data?.capabilities.verification&&<QueueCard title="Верифікації" count={data.counts.verification} meta="Особа · права · автомобіль" action="ВІДКРИТИ ЧЕРГУ" onPress={()=>router.push('/verification-review')}/>}
    {data?.capabilities.professionalCarriers&&<QueueCard title="ФОП / бізнес" count={data.counts.professionalCarriers} meta="Реквізити · статус особи · права · авто" action="ПЕРЕВІРИТИ ПРОФІЛІ" onPress={()=>router.push('/professional-review')}/>}
    {data?.capabilities.disputes&&<QueueCard title="Спори" count={data.counts.disputes} meta="Evidence · GPS · handover · рішення" action="РОЗГЛЯНУТИ СПОРИ" onPress={()=>router.push('/dispute-review')}/>}
    {data?.capabilities.finance&&<QueueCard title="Фінанси & ресурси" count={0} meta="GMV · маржа · API · інфраструктура" action="ВІДКРИТИ CONTROL CENTER" onPress={()=>router.push('/staff-finance')}/>}{data?.capabilities.readiness&&<QueueCard title="Production readiness" count={0} meta="Release gate · audit · funnel · errors · legal" action="ВІДКРИТИ RELEASE CONTROL" onPress={()=>router.push('/staff-readiness')}/>}{data?.capabilities.privacy&&<QueueCard title="Privacy requests" count={data.counts.privacy} meta="Access · correction · deletion · restriction" action="ВІДКРИТИ PRIVACY QUEUE" onPress={()=>router.push('/staff-privacy')}/>}
    {data?.capabilities.payoutIssues&&<QueueCard title="Проблемні виплати" count={data.counts.payoutIssues} meta="Failed / manual review · без ручного руху коштів" action="ВІДКРИТИ" onPress={()=>router.push('/payout-review')}/>}
    <Text style={s.section}>РОБОЧЕ СЕРЕДОВИЩЕ</Text>
    <View style={s.theme}><View style={{flex:1}}><Text style={s.themeTitle}>Тема</Text><Text style={s.themeMeta}>Налаштування тільки цього пристрою.</Text></View><View style={s.segment}><Pressable onPress={()=>void setMode('dark')} style={[s.seg,mode==='dark'&&s.segOn]}><Text style={[s.segText,mode==='dark'&&s.segTextOn]}>ТЕМНА</Text></Pressable><Pressable onPress={()=>void setMode('light')} style={[s.seg,mode==='light'&&s.segOn]}><Text style={[s.segText,mode==='light'&&s.segTextOn]}>СВІТЛА</Text></Pressable><Pressable onPress={()=>void setMode('badger')} style={[s.seg,mode==='badger'&&s.segOn]}><Text style={[s.segText,mode==='badger'&&s.segTextOn]}>BADGER</Text></Pressable></View></View>
    <Pressable style={s.logout} onPress={signOut}><Text style={s.logoutText}>ЗАВЕРШИТИ СЕСІЮ</Text><Text style={s.logoutText}>→</Text></Pressable>
  </ScrollView></Screen>;
}
function QueueCard({title,count,meta,action,onPress}:{title:string;count:number;meta:string;action:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.queue,pressed&&{opacity:.72}]}><View style={s.queueTop}><View><Text style={s.queueTitle}>{title}</Text><Text style={s.queueMeta}>{meta}</Text></View><View style={s.count}><Text style={s.countText}>{count}</Text></View></View><View style={s.div}/><View style={s.queueAction}><Text style={s.action}>{action}</Text><Text style={s.arrow}>→</Text></View></Pressable>}
const s=themedStyleSheet(()=>({head:{minHeight:120,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:31,fontWeight:'900',marginTop:5},subtitle:{color:colors.muted,fontSize:9,fontWeight:'800',marginTop:7},staffPill:{borderWidth:1,borderColor:colors.accent,borderRadius:radii.pill,paddingHorizontal:11,paddingVertical:7,backgroundColor:colors.accentSoft},staffPillText:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.1},err:{color:colors.danger,fontWeight:'800',marginBottom:10},hero:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:18},heroEye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.2},heroTitle:{color:colors.text,fontSize:22,fontWeight:'900',lineHeight:27,marginTop:8},heroBody:{color:colors.textSecondary,fontSize:11,lineHeight:18,marginTop:8},section:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginTop:22,marginBottom:8},queue:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:16,marginBottom:9},queueTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},queueTitle:{color:colors.text,fontSize:17,fontWeight:'900'},queueMeta:{color:colors.muted,fontSize:9,marginTop:5},count:{minWidth:46,height:46,borderRadius:15,backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.accent,alignItems:'center',justifyContent:'center'},countText:{color:colors.accent,fontSize:18,fontWeight:'900'},div:{height:1,backgroundColor:colors.border,marginVertical:13},queueAction:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},action:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:.8},arrow:{color:colors.accent,fontSize:17,fontWeight:'900'},theme:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:14,gap:12},themeTitle:{color:colors.text,fontSize:13,fontWeight:'900'},themeMeta:{color:colors.muted,fontSize:9,marginTop:4},segment:{flexDirection:'row',backgroundColor:colors.surfaceMuted,borderRadius:radii.md,padding:3,width:'100%'},seg:{flex:1,minHeight:37,borderRadius:9,alignItems:'center',justifyContent:'center'},segOn:{backgroundColor:colors.accent},segText:{color:colors.muted,fontSize:8,fontWeight:'900'},segTextOn:{color:colors.accentText},logout:{minHeight:54,borderWidth:1,borderColor:colors.danger,borderRadius:radii.md,marginTop:14,paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logoutText:{color:colors.danger,fontSize:9,fontWeight:'900',letterSpacing:.9}}));
