import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Linking, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiFetch, readJsonSafe } from '@/api/client';
import type { VerificationReviewCase } from '@/api/types';
import { colors, radii, themedStyleSheet } from '@/theme/tokens';
import { Screen } from '@/ui/screen';
import {useLiveVersion} from '@/live/live-context';

type Detail={id:string;subjectType:string;subjectId:string|null;status:string;assignedTo:string|null;user:{displayName:string;email:string|null;phone:string|null};documents:Array<{id:string;documentKind:string;mimeType:string;sizeBytes:number|null}>};
export default function VerificationReview(){const live=useLiveVersion('staff');
 const[queue,setQueue]=useState<VerificationReviewCase[]>([]);const[selected,setSelected]=useState<Detail|null>(null);const[reason,setReason]=useState('Перевірено вручну');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await apiFetch('/verification/review/queue');const d=await readJsonSafe<any>(r);if(!r.ok)throw new Error(d?.message??'Немає доступу');setQueue(d);setError('')}catch(e:any){setError(e?.message??'Помилка')}},[]);useFocusEffect(useCallback(()=>{void load()},[load,live]));
 async function openCase(id:string){setBusy(true);try{await apiFetch(`/verification/review/${id}/claim`,{method:'POST'});const r=await apiFetch(`/verification/review/${id}`);const d=await readJsonSafe<any>(r);if(!r.ok)throw new Error(d?.message??'Помилка');setSelected(d)}catch(e:any){setError(e?.message??'Помилка')}finally{setBusy(false)}}
 async function openDoc(id:string){if(!selected)return;const r=await apiFetch(`/verification/review/${selected.id}/documents/${id}/access-url`,{method:'POST',body:JSON.stringify({purpose:'manual verification review'})});const d=await readJsonSafe<any>(r);if(r.ok)await Linking.openURL(d.url);else setError(d?.message??'Помилка доступу')}
 async function decide(decision:'verified'|'rejected'|'needs_resubmission'){if(!selected)return;setBusy(true);try{const r=await apiFetch(`/verification/review/${selected.id}/decision`,{method:'POST',body:JSON.stringify({decision,reason})});const d=await readJsonSafe<any>(r);if(!r.ok)throw new Error(d?.message??'Помилка');setSelected(null);await load()}catch(e:any){setError(e?.message??'Помилка')}finally{setBusy(false)}}
 return <Screen><ScrollView contentContainerStyle={{paddingBottom:100}}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>←</Text></Pressable><View><Text style={s.eye}>STAFF ONLY</Text><Text style={s.title}>Verification queue</Text></View></View>{!!error&&<Text style={s.error}>{error}</Text>}{!selected?<>{queue.map(c=><Pressable key={c.id} onPress={()=>void openCase(c.id)} style={s.card}><Text style={s.cardTitle}>{c.user.displayName}</Text><Text style={s.meta}>{c.subjectType.toUpperCase()} · {c.status.toUpperCase()}</Text><Text style={s.meta}>{new Date(c.submittedAt).toLocaleString()}</Text></Pressable>)}{!queue.length&&<Text style={s.empty}>Черга порожня.</Text>}</>:<View style={s.card}><Text style={s.cardTitle}>{selected.user.displayName}</Text><Text style={s.meta}>{selected.user.phone??selected.user.email??'—'} · {selected.subjectType}</Text><Text style={s.section}>ДОКУМЕНТИ</Text>{selected.documents.map(d=><Pressable key={d.id} style={s.doc} onPress={()=>void openDoc(d.id)}><Text style={s.docText}>{d.documentKind}</Text><Text style={s.meta}>{d.mimeType} · {d.sizeBytes??0} B</Text></Pressable>)}<Text style={s.section}>КОМЕНТАР РІШЕННЯ</Text><TextInput value={reason} onChangeText={setReason} multiline style={s.input}/><View style={s.actions}><Pressable disabled={busy||reason.trim().length<3} style={[s.btn,s.okBtn]} onPress={()=>void decide('verified')}><Text style={s.btnText}>APPROVE</Text></Pressable><Pressable disabled={busy||reason.trim().length<3} style={s.btn} onPress={()=>void decide('needs_resubmission')}><Text style={s.btnText}>RESUBMIT</Text></Pressable><Pressable disabled={busy||reason.trim().length<3} style={[s.btn,s.badBtn]} onPress={()=>void decide('rejected')}><Text style={s.btnText}>REJECT</Text></Pressable></View></View>}</ScrollView></Screen>
}
const s=themedStyleSheet(()=>({header:{minHeight:88,flexDirection:'row',alignItems:'center',gap:14},back:{color:colors.text,fontSize:25,fontWeight:'900'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{color:colors.text,fontSize:25,fontWeight:'900'},error:{color:colors.danger,marginBottom:10,fontWeight:'800'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.lg,padding:15,marginBottom:9},cardTitle:{color:colors.text,fontSize:16,fontWeight:'900'},meta:{color:colors.muted,fontSize:9,marginTop:4},section:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.2,marginTop:18,marginBottom:7},doc:{borderWidth:1,borderColor:colors.border,borderRadius:radii.sm,padding:11,marginBottom:7},docText:{color:colors.text,fontSize:10,fontWeight:'900'},input:{minHeight:85,borderWidth:1,borderColor:colors.border,borderRadius:radii.sm,padding:10,color:colors.text,textAlignVertical:'top'},actions:{gap:8,marginTop:12},btn:{minHeight:46,borderRadius:radii.sm,backgroundColor:colors.surfaceRaised,alignItems:'center',justifyContent:'center'},okBtn:{backgroundColor:colors.accent},badBtn:{borderWidth:1,borderColor:colors.danger},btnText:{color:colors.text,fontSize:10,fontWeight:'900'},empty:{color:colors.muted,marginTop:20}}));
