import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiFetch } from '@/api/client';
import type { Cargo, CargoOffer } from '@/api/types';
import {colors,themedStyleSheet} from '@/theme/tokens';
import { Screen } from '@/ui/screen';
import {useLiveVersion} from '@/live/live-context';

export default function CargoDetail(){
  const {id}=useLocalSearchParams<{id:string}>();const live=useLiveVersion('cargo','deals');const[cargo,setCargo]=useState<Cargo|null>(null);const[offers,setOffers]=useState<CargoOffer[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');
  const load=useCallback(async()=>{if(!id)return;setError('');try{const [c,o]=await Promise.all([apiFetch(`/cargo/${id}`),apiFetch(`/offers/cargo/${id}`)]);const cd=await c.json(),od=await o.json();if(!c.ok)throw new Error(cd?.message??'Не вдалося завантажити вантаж');if(!o.ok)throw new Error(od?.message??'Не вдалося завантажити пропозиції');setCargo(cd);setOffers(od);}catch(e){setError(e instanceof Error?e.message:'Помилка');}},[id]);
  useFocusEffect(useCallback(()=>{void load();},[load]));useEffect(()=>{void load()},[live,load]);

  async function removeCargo(){if(!id)return;Alert.alert('Видалити вантаж?','Це можна зробити лише до прийняття угоди. Дію не можна скасувати.',[{text:'Скасувати',style:'cancel'},{text:'Видалити',style:'destructive',onPress:async()=>{setBusy('delete');try{const r=await apiFetch(`/cargo/${id}`,{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d?.message??'Не вдалося видалити');router.replace('/(tabs)')}catch(e){setError(e instanceof Error?e.message:'Помилка')}finally{setBusy('')}}}]);}
  async function act(offerId:string,action:'accept'|'reject'){setBusy(offerId+action);try{const r=await apiFetch(action==='accept'?'/deals/accept-offer':`/offers/${offerId}/reject`,{method:'POST',body:action==='accept'?JSON.stringify({offerId}):undefined});const d=await r.json();if(!r.ok)throw new Error(d?.message??'Операція не виконана');if(action==='accept')router.replace({pathname:'/deal/[id]',params:{id:d.id}});else await load();}catch(e){setError(e instanceof Error?e.message:'Помилка');}finally{setBusy('');}}
  return <Screen><ScrollView contentContainerStyle={{paddingBottom:30}}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>←</Text></Pressable><View><Text style={s.eye}>МІЙ ВАНТАЖ</Text><Text style={s.title}>{cargo?.title??'Завантаження...'}</Text></View></View>{!!error&&<Text style={s.error}>{error}</Text>}{cargo&&<><View style={s.summary}><View style={s.row}><Text style={s.route}>{cargo.pickup.publicLabel} → {cargo.delivery.publicLabel}</Text><Text style={s.price}>{Math.round(cargo.rewardMinor/100)} ₴</Text></View><Text style={s.meta}>{cargo.status.toUpperCase()} · {cargo.weightKg?`${cargo.weightKg} кг`:'вага не вказана'}</Text>{cargo.declaredValueMinor!=null&&<Text style={s.meta}>Оціночна вартість: {Math.round(cargo.declaredValueMinor/100).toLocaleString('uk-UA')} ₴ · довідково</Text>}{['draft','published'].includes(cargo.status)&&<View style={s.manage}><Pressable onPress={()=>router.push({pathname:'/edit-cargo/[id]',params:{id:String(id)}})} style={s.manageButton}><Text style={s.manageText}>РЕДАГУВАТИ</Text></Pressable><Pressable onPress={removeCargo} style={s.deleteButton}><Text style={s.deleteText}>ВИДАЛИТИ</Text></Pressable></View>}</View><View style={s.section}><Text style={s.eye}>ПРОПОЗИЦІЇ ПЕРЕВІЗНИКІВ</Text><Text style={s.sectionTitle}>{offers.filter(x=>x.status==='pending').length} активних</Text></View>{offers.map(o=><View key={o.id} style={s.card}><View style={s.row}><View><Text style={s.driver}>{o.driver.displayName}</Text><Text style={s.meta}>{o.driver.verificationStatus.toUpperCase()} · {o.status.toUpperCase()}</Text></View><Text style={s.price}>{Math.round(o.amountMinor/100)} ₴</Text></View>{o.message&&<Text style={s.message}>{o.message}</Text>}{o.status==='pending'&&<View style={s.actions}><Pressable disabled={!!busy} onPress={()=>act(o.id,'reject')} style={s.secondary}><Text style={s.secondaryText}>ВІДХИЛИТИ</Text></Pressable><Pressable disabled={!!busy} onPress={()=>act(o.id,'accept')} style={s.primary}><Text style={s.primaryText}>{busy===o.id+'accept'?'...':'ПРИЙНЯТИ'}</Text></Pressable></View>}</View>)}{!offers.length&&<View style={s.empty}><Text style={s.meta}>Пропозицій поки немає. Вони з’являться тут, коли водій запропонує перевезення зі своєї поїздки.</Text></View>}</>}</ScrollView></Screen>;
}
const s=themedStyleSheet(()=>({header:{minHeight:84,flexDirection:'row',alignItems:'center',gap:15,borderBottomWidth:1,borderBottomColor:colors.border},back:{width:40,height:40,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},backText:{color:colors.text,fontSize:20,fontWeight:'900'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{color:colors.text,fontSize:20,fontWeight:'900',marginTop:4},error:{color:colors.danger,fontSize:12,marginTop:10},summary:{padding:17,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,marginTop:12},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},route:{color:colors.text,fontSize:15,fontWeight:'900',flex:1},price:{color:colors.accent,fontSize:19,fontWeight:'900'},meta:{color:colors.textSecondary,fontSize:10,marginTop:5},section:{marginTop:20,marginBottom:8},sectionTitle:{color:colors.text,fontSize:20,fontWeight:'900',marginTop:4},card:{borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border,paddingVertical:15,marginBottom:8},driver:{color:colors.text,fontSize:15,fontWeight:'900'},message:{color:colors.textSecondary,fontSize:12,lineHeight:18,marginTop:10},actions:{flexDirection:'row',gap:8,marginTop:13},secondary:{flex:1,minHeight:44,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.text,fontSize:10,fontWeight:'900'},primary:{flex:1,minHeight:44,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.accentText,fontSize:10,fontWeight:'900'},empty:{borderWidth:1,borderColor:colors.border,padding:18},manage:{flexDirection:'row',gap:8,marginTop:13},manageButton:{flex:1,minHeight:42,borderWidth:1,borderColor:colors.accent,alignItems:'center',justifyContent:'center'},manageText:{color:colors.accent,fontSize:9,fontWeight:'900'},deleteButton:{flex:1,minHeight:42,borderWidth:1,borderColor:colors.danger,alignItems:'center',justifyContent:'center'},deleteText:{color:colors.danger,fontSize:9,fontWeight:'900'}}));
