import { ConflictException, ForbiddenException, Inject, Injectable } from '@nestjs/common';
type QueryExecutor={query:(text:string,values?:any[])=>Promise<{rows:any[]}>};
import { DatabaseService } from '../database/database.service';

export type CarrierMode='casual'|'professional';
const POLICY_VERSION=1;
const CASUAL={maxFutureTrips:2,maxTrips30d:8,maxCompletedDeliveries30d:12,maxDetourKm:30,costPerKmMinor:450,minTripCostMinor:10000};
@Injectable() export class CarrierModeService{
 constructor(@Inject(DatabaseService) private readonly db:DatabaseService){}
 async get(userId:string,q:QueryExecutor=this.db){await q.query(`INSERT INTO carrier_profile(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[userId]);const r=await q.query('SELECT * FROM carrier_profile WHERE user_id=$1',[userId]);return this.dto(r.rows[0]);}
 async setMode(userId:string,input:{mode:CarrierMode;acceptCasualPolicy?:boolean;businessName?:string;businessRegistrationRef?:string}){return this.db.transaction(async c=>{await c.query(`INSERT INTO carrier_profile(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[userId]);if(input.mode==='casual'){if(!input.acceptCasualPolicy)throw new ConflictException({code:'CASUAL_POLICY_ACCEPTANCE_REQUIRED',message:'Підтвердіть правила непрофесійних попутних поїздок'});await c.query(`UPDATE carrier_profile SET mode='casual',accepted_casual_policy_at=now(),policy_version=$2,updated_at=now() WHERE user_id=$1`,[userId,POLICY_VERSION]);}else{if((input.businessName??'').trim().length<2||(input.businessRegistrationRef??'').trim().length<5)throw new ConflictException({code:'BUSINESS_DETAILS_REQUIRED',message:'Для професійного режиму вкажіть назву/ПІБ ФОП та реєстраційний ідентифікатор'});await c.query(`UPDATE carrier_profile SET mode='professional',business_name=$2,business_registration_ref=$3,professional_status=CASE WHEN business_name IS DISTINCT FROM $2 OR business_registration_ref IS DISTINCT FROM $3 THEN 'pending' ELSE CASE WHEN professional_status='verified' THEN 'verified' ELSE 'pending' END END,updated_at=now() WHERE user_id=$1`,[userId,input.businessName!.trim(),input.businessRegistrationRef!.trim()]);}return this.get(userId,c);});}
 async assertTripAllowed(userId:string,distanceM:number,maxDetourKm:number,q:QueryExecutor=this.db){const p=await this.get(userId,q);if(p.mode==='professional'){if(p.professionalStatus!=='verified')throw new ForbiddenException({code:'PROFESSIONAL_VERIFICATION_REQUIRED',message:'Професійний режим очікує перевірки ФОП/бізнесу'});return {mode:'professional' as const,costCapMinor:null,policyVersion:POLICY_VERSION};}if(!p.acceptedCasualPolicyAt)throw new ForbiddenException({code:'CASUAL_POLICY_REQUIRED',message:'Спочатку прийміть правила попутного режиму'});if(maxDetourKm>CASUAL.maxDetourKm)throw new ForbiddenException({code:'CASUAL_DETOUR_LIMIT',message:`Для попутного режиму максимальне відхилення — ${CASUAL.maxDetourKm} км`});const counts=await q.query(`SELECT (SELECT count(*) FROM trip WHERE driver_id=$1 AND status='published' AND departure_from>now())::int future,(SELECT count(*) FROM trip WHERE driver_id=$1 AND created_at>=now()-interval '30 days')::int trips30,(SELECT count(*) FROM deal WHERE driver_id=$1 AND status='completed' AND completed_at>=now()-interval '30 days')::int deals30`,[userId]);const x=counts.rows[0];if(Number(x.future)>=CASUAL.maxFutureTrips)throw new ForbiddenException({code:'CASUAL_ACTIVE_TRIP_LIMIT',message:`Попутний режим: не більше ${CASUAL.maxFutureTrips} майбутніх активних поїздок`});if(Number(x.trips30)>=CASUAL.maxTrips30d)throw new ForbiddenException({code:'CASUAL_MONTHLY_TRIP_LIMIT',message:`Досягнуто ліміт ${CASUAL.maxTrips30d} поїздок за 30 днів. Для регулярної діяльності перейдіть у режим ФОП`});if(Number(x.deals30)>=CASUAL.maxCompletedDeliveries30d)throw new ForbiddenException({code:'CASUAL_ACTIVITY_LIMIT',message:'Активність схожа на професійну. Для продовження потрібен режим ФОП'});const km=Math.max(1,Math.ceil(distanceM/1000));return {mode:'casual' as const,costCapMinor:Math.max(CASUAL.minTripCostMinor,km*CASUAL.costPerKmMinor),policyVersion:POLICY_VERSION};}
 async assertOfferAllowed(userId:string,tripId:string,amountMinor:number,q:QueryExecutor=this.db){const p=await this.get(userId,q);if(p.mode==='professional'){if(p.professionalStatus!=='verified')throw new ForbiddenException({code:'PROFESSIONAL_VERIFICATION_REQUIRED',message:'Професійний профіль ще не підтверджено'});return 'professional' as const;}const t=await q.query('SELECT casual_cost_cap_minor FROM trip WHERE id=$1 AND driver_id=$2',[tripId,userId]);const cap=Number(t.rows[0]?.casual_cost_cap_minor??0);const used=await q.query(`SELECT COALESCE(sum(amount_minor),0)::bigint used FROM cargo_offer WHERE trip_id=$1 AND driver_id=$2 AND status IN ('pending','accepted')`,[tripId,userId]);const remaining=Math.max(0,cap-Number(used.rows[0]?.used??0));if(amountMinor>remaining)throw new ForbiddenException({code:'CASUAL_COST_SHARING_CAP',message:`Попутний режим не дозволяє перетворювати поїздку на заробіток. Доступний залишок компенсації витрат: ${(remaining/100).toFixed(2)} грн`});return 'casual' as const;}
 async listProfessionalPending(){const r=await this.db.query<any>(`SELECT cp.user_id AS "userId",cp.business_name AS "businessName",cp.business_registration_ref AS "businessRegistrationRef",cp.professional_status AS "professionalStatus",cp.updated_at AS "submittedAt",u.display_name AS "displayName",u.phone_e164 AS "phone",iv.status AS "identityStatus",dl.status AS "licenseStatus",(SELECT count(*)::int FROM vehicle v WHERE v.owner_id=cp.user_id) AS "vehicleCount",(SELECT count(*)::int FROM vehicle_verification vv JOIN vehicle v ON v.id=vv.vehicle_id WHERE v.owner_id=cp.user_id AND vv.status='verified') AS "verifiedVehicleCount" FROM carrier_profile cp JOIN app_user u ON u.id=cp.user_id LEFT JOIN identity_verification_profile iv ON iv.user_id=cp.user_id LEFT JOIN driver_license_verification dl ON dl.user_id=cp.user_id WHERE cp.mode='professional' AND cp.professional_status='pending' ORDER BY cp.updated_at ASC LIMIT 100`);return r.rows.map((x:any)=>({...x,vehicleCount:Number(x.vehicleCount??0),verifiedVehicleCount:Number(x.verifiedVehicleCount??0)}));}
 async reviewProfessional(reviewerId:string,userId:string,decision:'verified'|'rejected',note:string){const r=await this.db.query(`UPDATE carrier_profile SET professional_status=$2,professional_note=$3,professional_reviewed_at=now(),professional_reviewed_by=$4,updated_at=now() WHERE user_id=$1 AND mode='professional' AND professional_status='pending' RETURNING user_id`,[userId,decision,note,reviewerId]);if(!r.rows[0])throw new ConflictException({code:'PROFESSIONAL_REVIEW_NOT_PENDING',message:'Професійний профіль уже розглянуто або він більше не очікує перевірки'});return {ok:true,status:decision};}
 policy(){return {version:POLICY_VERSION,...CASUAL,principles:['Поїздка планується незалежно від вантажу','Компенсація не повинна перетворювати попутну поїздку на систематичний заробіток','CargoGo може обмежити активність, що має ознаки професійної','Професійна діяльність переводиться в режим ФОП/бізнес']};}
 private dto(r:any){return {mode:r.mode as CarrierMode,professionalStatus:r.professional_status,businessName:r.business_name,businessRegistrationRef:r.business_registration_ref,professionalNote:r.professional_note,acceptedCasualPolicyAt:r.accepted_casual_policy_at,policyVersion:r.policy_version,policy:this.policy()};}
}
