import { ConflictException, ForbiddenException, Inject, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DatabaseService } from '../database/database.service';
type QueryExecutor={query:(text:string,values?:any[])=>Promise<{rows:any[]}>};
export type CarrierMode='casual'|'professional';
const POLICY_VERSION=2;
const CASUAL={maxFutureTrips:2,maxTrips30d:8,maxCompletedDeliveries30d:12,maxDetourKm:30,maintenanceMinorPerKm:180,depreciationMinorPerKm:160,reserveBps:1200,minTripCostMinor:10000};
@Injectable() export class CarrierModeService{
 constructor(@Inject(DatabaseService) private readonly db:DatabaseService,@Inject(ConfigService)private readonly config:ConfigService){}
 async get(userId:string,q:QueryExecutor=this.db){await q.query(`INSERT INTO carrier_profile(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[userId]);const r=await q.query('SELECT * FROM carrier_profile WHERE user_id=$1',[userId]);return this.dto(r.rows[0]);}
 async setMode(userId:string,input:{mode:CarrierMode;acceptCasualPolicy?:boolean;businessName?:string;businessRegistrationRef?:string}){return this.db.transaction(async c=>{await c.query(`INSERT INTO carrier_profile(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[userId]);if(input.mode==='casual'){if(!input.acceptCasualPolicy)throw new ConflictException({code:'CASUAL_POLICY_ACCEPTANCE_REQUIRED',message:'Підтвердіть правила непрофесійних попутних поїздок'});await c.query(`UPDATE carrier_profile SET mode='casual',accepted_casual_policy_at=now(),policy_version=$2,updated_at=now() WHERE user_id=$1`,[userId,POLICY_VERSION]);}else{if((input.businessName??'').trim().length<2||(input.businessRegistrationRef??'').trim().length<5)throw new ConflictException({code:'BUSINESS_DETAILS_REQUIRED',message:'Для професійного режиму вкажіть назву/ПІБ ФОП та реєстраційний ідентифікатор'});await c.query(`UPDATE carrier_profile SET mode='professional',business_name=$2,business_registration_ref=$3,professional_status=CASE WHEN business_name IS DISTINCT FROM $2 OR business_registration_ref IS DISTINCT FROM $3 THEN 'pending' ELSE CASE WHEN professional_status='verified' THEN 'verified' ELSE 'pending' END END,updated_at=now() WHERE user_id=$1`,[userId,input.businessName!.trim(),input.businessRegistrationRef!.trim()]);}return this.get(userId,c);});}
 async assertTripAllowed(userId:string,vehicle:any,distanceM:number,durationS:number,maxDetourKm:number,q:QueryExecutor=this.db){const p=await this.get(userId,q);if(p.mode==='professional'){if(p.professionalStatus!=='verified')throw new ForbiddenException({code:'PROFESSIONAL_VERIFICATION_REQUIRED',message:'Професійний режим очікує перевірки ФОП/бізнесу'});return {mode:'professional' as const,costCapMinor:null,policyVersion:POLICY_VERSION,costBreakdown:null};}if(!p.acceptedCasualPolicyAt)throw new ForbiddenException({code:'CASUAL_POLICY_REQUIRED',message:'Спочатку прийміть правила попутного режиму'});if(maxDetourKm>CASUAL.maxDetourKm)throw new ForbiddenException({code:'CASUAL_DETOUR_LIMIT',message:`Для попутного режиму максимальне відхилення — ${CASUAL.maxDetourKm} км`});const counts=await q.query(`SELECT (SELECT count(*) FROM trip WHERE driver_id=$1 AND status='published' AND departure_from>now())::int future,(SELECT count(*) FROM trip WHERE driver_id=$1 AND created_at>=now()-interval '30 days')::int trips30,(SELECT count(*) FROM deal WHERE driver_id=$1 AND status='completed' AND completed_at>=now()-interval '30 days')::int deals30`,[userId]);const x=counts.rows[0];if(Number(x.future)>=CASUAL.maxFutureTrips)throw new ForbiddenException({code:'CASUAL_ACTIVE_TRIP_LIMIT',message:`Попутний режим: не більше ${CASUAL.maxFutureTrips} майбутніх активних поїздок`});if(Number(x.trips30)>=CASUAL.maxTrips30d)throw new ForbiddenException({code:'CASUAL_MONTHLY_TRIP_LIMIT',message:`Досягнуто ліміт ${CASUAL.maxTrips30d} поїздок за 30 днів. Для регулярної діяльності перейдіть у режим ФОП`});if(Number(x.deals30)>=CASUAL.maxCompletedDeliveries30d)throw new ForbiddenException({code:'CASUAL_ACTIVITY_LIMIT',message:'Активність схожа на професійну. Для продовження потрібен режим ФОП'});const estimate=this.estimateCost(vehicle,distanceM,0,durationS);return {mode:'casual' as const,costCapMinor:estimate.capMinor,policyVersion:POLICY_VERSION,costBreakdown:estimate};}
 async recalculateTripPolicy(userId:string,vehicle:any,distanceM:number,durationS:number,maxDetourKm:number,q:QueryExecutor=this.db){const p=await this.get(userId,q);if(p.mode==='professional'){if(p.professionalStatus!=='verified')throw new ForbiddenException({code:'PROFESSIONAL_VERIFICATION_REQUIRED',message:'Професійний режим очікує перевірки ФОП/бізнесу'});return {mode:'professional' as const,costCapMinor:null,policyVersion:POLICY_VERSION,costBreakdown:null};}if(!p.acceptedCasualPolicyAt)throw new ForbiddenException({code:'CASUAL_POLICY_REQUIRED',message:'Спочатку прийміть правила попутного режиму'});if(maxDetourKm>CASUAL.maxDetourKm)throw new ForbiddenException({code:'CASUAL_DETOUR_LIMIT',message:`Для попутного режиму максимальне відхилення — ${CASUAL.maxDetourKm} км`});const estimate=this.estimateCost(vehicle,distanceM,0,durationS);return {mode:'casual' as const,costCapMinor:estimate.capMinor,policyVersion:POLICY_VERSION,costBreakdown:estimate};}
 async assertOfferAllowed(userId:string,tripId:string,cargoId:string,amountMinor:number,q:QueryExecutor=this.db){const p=await this.get(userId,q);if(p.mode==='professional'){if(p.professionalStatus!=='verified')throw new ForbiddenException({code:'PROFESSIONAL_VERIFICATION_REQUIRED',message:'Професійний профіль ще не підтверджено'});return {mode:'professional' as const,capMinor:null,remainingMinor:null};}const t=await q.query(`SELECT t.route_distance_m,t.route_duration_s,v.*,c.weight_kg proposed_weight FROM trip t JOIN vehicle v ON v.id=t.vehicle_id JOIN cargo c ON c.id=$3 WHERE t.id=$1 AND t.driver_id=$2`,[tripId,userId,cargoId]);if(!t.rows[0])throw new ForbiddenException({code:'CASUAL_TRIP_CONTEXT_MISSING',message:'Не вдалося розрахувати ліміт попутної поїздки'});const existing=await q.query(`SELECT COALESCE(sum(o.amount_minor),0)::bigint used,COALESCE(sum(c.weight_kg),0)::numeric load FROM cargo_offer o JOIN cargo c ON c.id=o.cargo_id WHERE o.trip_id=$1 AND o.driver_id=$2 AND o.cargo_id<>$3 AND o.status IN ('pending','accepted')`,[tripId,userId,cargoId]);const row=t.rows[0],e=existing.rows[0]??{};const totalLoad=Math.max(0,Number(e.load??0)+Number(row.proposed_weight??0));const estimate=this.estimateCost(row,Number(row.route_distance_m??0),totalLoad,Number(row.route_duration_s??0));const remaining=Math.max(0,estimate.capMinor-Number(e.used??0));if(amountMinor>remaining)throw new ForbiddenException({code:'CASUAL_COST_SHARING_CAP',message:`Попутний режим: пропозиція перевищує розрахункову компенсацію витрат. Доступно до ${(remaining/100).toFixed(2)} грн`,details:estimate});return {mode:'casual' as const,capMinor:estimate.capMinor,remainingMinor:remaining,estimate};}
 private estimateCost(v:any,distanceM:number,loadKg:number,durationS=0){
  const km=Math.max(1,distanceM/1000);const fuelType=v.fuel_type??'petrol';const curb=Math.max(500,Number(v.curb_weight_kg??1500));const gross=Math.max(curb,Number(v.gross_weight_kg??(curb+Number(v.max_payload_kg??0))));const legalPayload=Math.max(0,Math.min(Number(v.max_payload_kg??(gross-curb)),gross-curb||Number(v.max_payload_kg??0)));const payload=Math.max(0,Math.min(legalPayload||loadKg,loadKg));
  const loadFactor=1+Math.min(.28,(payload/curb)*.35);const avgSpeed=durationS>0?km/(durationS/3600):70;const routeFactor=avgSpeed<30?1.15:avgSpeed<50?1.08:avgSpeed<65?1.03:1;const weightWearFactor=Math.min(1.25,Math.max(.9,1+(curb-1400)/10000));
  let energyMinor=0;let unit='L';let rateMinor=0;let declaredConsumption=0;let effectiveConsumption=0;let engineBaseline:number|null=null;
  if(fuelType==='electric'){unit='kWh';rateMinor=this.config.get<number>('REFERENCE_ELECTRICITY_MINOR_PER_KWH')??500;declaredConsumption=Number(v.energy_consumption_kwh_100??18);effectiveConsumption=declaredConsumption*loadFactor*routeFactor;energyMinor=Math.round(km/100*effectiveConsumption*rateMinor);}else{
    const rates:any={petrol:this.config.get<number>('REFERENCE_PETROL_MINOR_PER_LITER')??6000,diesel:this.config.get<number>('REFERENCE_DIESEL_MINOR_PER_LITER')??5800,lpg:this.config.get<number>('REFERENCE_LPG_MINOR_PER_LITER')??3400,petrol_lpg:this.config.get<number>('REFERENCE_LPG_MINOR_PER_LITER')??3400,hybrid:this.config.get<number>('REFERENCE_PETROL_MINOR_PER_LITER')??6000,plug_in_hybrid:this.config.get<number>('REFERENCE_PETROL_MINOR_PER_LITER')??6000};rateMinor=rates[fuelType]??6000;const liters=Math.max(.5,Number(v.engine_displacement_cc??1600)/1000);const base=fuelType==='diesel'?4.2+liters*1.25:fuelType==='hybrid'||fuelType==='plug_in_hybrid'?3.5+liters*.95:fuelType==='lpg'||fuelType==='petrol_lpg'?6+liters*1.55:5+liters*1.45;engineBaseline=Number(base.toFixed(2));declaredConsumption=Number(v.avg_consumption_per_100??engineBaseline);const sanityFloor=engineBaseline*.72;effectiveConsumption=Math.max(declaredConsumption,sanityFloor)*loadFactor*routeFactor;energyMinor=Math.round(km/100*effectiveConsumption*rateMinor);
  }
  const maintenanceMinor=Math.round(km*CASUAL.maintenanceMinorPerKm*weightWearFactor);const depreciationMinor=Math.round(km*CASUAL.depreciationMinorPerKm*weightWearFactor);const subtotal=energyMinor+maintenanceMinor+depreciationMinor;const reserveMinor=Math.round(subtotal*CASUAL.reserveBps/10000);const capMinor=Math.max(CASUAL.minTripCostMinor,subtotal+reserveMinor);
  return {policyVersion:POLICY_VERSION,distanceKm:Number(km.toFixed(1)),averageSpeedKmh:Number(avgSpeed.toFixed(1)),fuelType,engineDisplacementCc:v.engine_displacement_cc??null,declaredConsumptionPer100:declaredConsumption,effectiveConsumptionPer100:Number(effectiveConsumption.toFixed(2)),engineBaselinePer100:engineBaseline,energyUnit:unit,referenceRateMinor:rateMinor,curbWeightKg:curb,grossWeightKg:gross,loadKg:payload,loadFactor:Number(loadFactor.toFixed(3)),routeFactor,weightWearFactor:Number(weightWearFactor.toFixed(3)),energyMinor,maintenanceMinor,depreciationMinor,reserveMinor,capMinor};
 }
 async listProfessionalPending(){const r=await this.db.query<any>(`SELECT cp.user_id AS "userId",cp.business_name AS "businessName",cp.business_registration_ref AS "businessRegistrationRef",cp.professional_status AS "professionalStatus",cp.updated_at AS "submittedAt",u.display_name AS "displayName",u.phone_e164 AS "phone",iv.status AS "identityStatus",dl.status AS "licenseStatus",(SELECT count(*)::int FROM vehicle v WHERE v.owner_id=cp.user_id) AS "vehicleCount",(SELECT count(*)::int FROM vehicle_verification vv JOIN vehicle v ON v.id=vv.vehicle_id WHERE v.owner_id=cp.user_id AND vv.status='verified') AS "verifiedVehicleCount" FROM carrier_profile cp JOIN app_user u ON u.id=cp.user_id LEFT JOIN identity_verification_profile iv ON iv.user_id=cp.user_id LEFT JOIN driver_license_verification dl ON dl.user_id=cp.user_id WHERE cp.mode='professional' AND cp.professional_status='pending' ORDER BY cp.updated_at ASC LIMIT 100`);return r.rows.map((x:any)=>({...x,vehicleCount:Number(x.vehicleCount??0),verifiedVehicleCount:Number(x.verifiedVehicleCount??0)}));}
 async reviewProfessional(reviewerId:string,userId:string,decision:'verified'|'rejected',note:string){const r=await this.db.query(`UPDATE carrier_profile SET professional_status=$2,professional_note=$3,professional_reviewed_at=now(),professional_reviewed_by=$4,updated_at=now() WHERE user_id=$1 AND mode='professional' AND professional_status='pending' RETURNING user_id`,[userId,decision,note,reviewerId]);if(!r.rows[0])throw new ConflictException({code:'PROFESSIONAL_REVIEW_NOT_PENDING',message:'Професійний профіль уже розглянуто або він більше не очікує перевірки'});return {ok:true,status:decision};}
 policy(){return {version:POLICY_VERSION,...CASUAL,principles:['Поїздка планується незалежно від вантажу','Ліміт компенсації враховує маршрут, тип пального, реальну витрату, масу авто та вантажу, ТО, амортизацію і резерв','Компенсація не повинна перетворювати попутну поїздку на систематичний заробіток','Професійна діяльність переводиться в режим ФОП/бізнес']};}
 private dto(r:any){return {mode:r.mode as CarrierMode,professionalStatus:r.professional_status,businessName:r.business_name,businessRegistrationRef:r.business_registration_ref,professionalNote:r.professional_note,acceptedCasualPolicyAt:r.accepted_casual_policy_at,policyVersion:r.policy_version,policy:this.policy()};}
}
