import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { DatabaseService } from '../database/database.service';
import type { RequestUser } from '../common/request-user';
import { LEGAL_DOCUMENTS, LEGAL_VERSION } from '../legal/legal.documents';
import { createHash } from 'node:crypto';

@Injectable()
export class OpsService{
 constructor(private readonly db:DatabaseService,private readonly config:ConfigService){}
 async reportClientError(user:RequestUser,input:any){const message=String(input?.message??'').slice(0,2000);if(!message)return{ok:false};const errorName=String(input?.errorName??'ClientError').slice(0,120);const screen=String(input?.screen??'').slice(0,200)||null;const fingerprint=createHash('sha256').update(`${errorName}|${screen??''}|${message}`).digest('hex').slice(0,40);await this.db.query(`INSERT INTO client_error_event(user_id,session_id,app_version,platform,screen,error_name,message,stack,metadata,severity,fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,[user.id,user.sessionId,String(input?.appVersion??'').slice(0,80)||null,String(input?.platform??'').slice(0,30)||null,screen,errorName,message,String(input?.stack??'').slice(0,10000)||null,JSON.stringify(input?.metadata??{}),['info','warning','error','critical'].includes(input?.severity)?input.severity:'error',fingerprint]);return{ok:true,fingerprint}}

 async diagnostics(user:RequestUser){this.assertStaff(user);const [client,server,counts]=await Promise.all([
  this.db.query<any>(`SELECT id,'client' source,severity,app_version AS "appVersion",platform,screen,NULL::text method,NULL::text path,NULL::int AS "statusCode",error_name AS "errorName",message,fingerprint,metadata,resolved_at AS "resolvedAt",resolution_note AS "resolutionNote",created_at AS "createdAt" FROM client_error_event ORDER BY created_at DESC LIMIT 100`),
  this.db.query<any>(`SELECT id,'server' source,severity,NULL::text AS "appVersion",NULL::text platform,NULL::text screen,method,path,status_code AS "statusCode",error_name AS "errorName",message,fingerprint,metadata,resolved_at AS "resolvedAt",resolution_note AS "resolutionNote",created_at AS "createdAt" FROM server_diagnostic_event ORDER BY created_at DESC LIMIT 100`),
  this.db.query<any>(`SELECT (SELECT count(*) FROM client_error_event WHERE resolved_at IS NULL)::int client_open,(SELECT count(*) FROM server_diagnostic_event WHERE resolved_at IS NULL)::int server_open,(SELECT count(*) FROM client_error_event WHERE created_at>=now()-interval '24 hours')::int client_24h,(SELECT count(*) FROM server_diagnostic_event WHERE created_at>=now()-interval '24 hours')::int server_24h`)
 ]);const items=[...client.rows,...server.rows].sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,150);const grouped=new Map<string,{fingerprint:string;source:string;message:string;errorName:string|null;count:number;lastSeen:string;open:number}>();for(const x of items){const key=x.fingerprint||`${x.source}:${x.errorName}:${x.message}`;const g=grouped.get(key)??{fingerprint:key,source:x.source,message:x.message,errorName:x.errorName??null,count:0,lastSeen:x.createdAt,open:0};g.count++;if(!x.resolvedAt)g.open++;if(String(x.createdAt)>String(g.lastSeen))g.lastSeen=x.createdAt;grouped.set(key,g)}return{generatedAt:new Date().toISOString(),counts:{clientOpen:Number(counts.rows[0]?.client_open??0),serverOpen:Number(counts.rows[0]?.server_open??0),client24h:Number(counts.rows[0]?.client_24h??0),server24h:Number(counts.rows[0]?.server_24h??0)},groups:[...grouped.values()].sort((a,b)=>b.open-a.open||b.count-a.count).slice(0,30),items};}
 async resolveDiagnostic(user:RequestUser,source:'client'|'server',id:number,note:string){this.assertStaff(user);const table=source==='client'?'client_error_event':'server_diagnostic_event';const r=await this.db.query<any>(`UPDATE ${table} SET resolved_at=now(),resolved_by=$2,resolution_note=$3 WHERE id=$1 AND resolved_at IS NULL RETURNING id`,[id,user.id,note]);if(!r.rowCount)throw new NotFoundException({code:'DIAGNOSTIC_NOT_FOUND',message:'Diagnostic event not found or already resolved'});await this.db.query(`INSERT INTO audit_event(actor_user_id,session_id,event_type,entity_type,metadata) VALUES($1,$2,'diagnostic.resolved','diagnostic_event',$3::jsonb)`,[user.id,user.sessionId,JSON.stringify({source,id,note})]);return{ok:true,source,id};}
 private assertStaff(user:RequestUser){if(!['reviewer','admin'].includes(user.staffRole??''))throw new ForbiddenException({code:'OPS_STAFF_REQUIRED',message:'Reviewer/admin required'})}
 async readiness(user:RequestUser){this.assertStaff(user);
  const [funnel,audit,errors,push,legal,privacy]=await Promise.all([
   this.db.query<any>(`SELECT (SELECT count(*) FROM app_user)::int users,(SELECT count(*) FROM app_user WHERE verification_status='verified')::int verified,(SELECT count(*) FROM cargo)::int cargo,(SELECT count(*) FROM trip)::int trips,(SELECT count(*) FROM cargo_offer)::int offers,(SELECT count(*) FROM deal)::int deals,(SELECT count(*) FROM deal WHERE status='completed')::int completed`),
   this.db.query<any>(`SELECT a.id,a.event_type AS "eventType",a.entity_type AS "entityType",a.entity_id AS "entityId",a.metadata,a.created_at AS "createdAt",u.display_name AS "actorName" FROM audit_event a LEFT JOIN app_user u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 40`),
   this.db.query<any>(`SELECT ((SELECT count(*) FROM client_error_event WHERE created_at>=now()-interval '24 hours')+(SELECT count(*) FROM server_diagnostic_event WHERE created_at>=now()-interval '24 hours'))::int errors24h,((SELECT count(*) FROM client_error_event WHERE created_at>=now()-interval '7 days')+(SELECT count(*) FROM server_diagnostic_event WHERE created_at>=now()-interval '7 days'))::int errors7d,(SELECT count(*) FROM client_error_event WHERE resolved_at IS NULL)::int client_open,(SELECT count(*) FROM server_diagnostic_event WHERE resolved_at IS NULL)::int server_open`),
   this.db.query<any>(`SELECT count(*) FILTER(WHERE delivered_at IS NULL AND attempts<5)::int pending,count(*) FILTER(WHERE delivered_at IS NULL AND attempts>=5)::int failed FROM push_delivery_outbox`),
   this.db.query<any>(`SELECT document_key,count(*)::int acceptances FROM legal_acceptance WHERE document_version=$1 GROUP BY document_key`,[LEGAL_VERSION]),
   this.db.query<any>(`SELECT count(*) FILTER(WHERE status IN('open','in_review'))::int open FROM privacy_request`)
  ]);
  const env={nodeEnv:this.config.get('NODE_ENV'),paymentsMode:this.config.get('PAYMENTS_MODE'),payoutsMode:this.config.get('PAYOUTS_MODE'),kycMode:this.config.get('KYC_MODE'),verificationEnforcement:this.config.get('VERIFICATION_ENFORCEMENT'),publicBaseUrl:this.config.get('PUBLIC_BASE_URL'),routingProvider:this.config.get('ROUTING_PROVIDER'),mapboxConfigured:!!this.config.get('MAPBOX_ACCESS_TOKEN')};
  const f=funnel.rows[0]??{};const checks=[
   {key:'db',label:'Database/schema',status:'pass',detail:'API responded and readiness query succeeded'},
   {key:'verification',label:'Verification enforcement',status:env.verificationEnforcement==='on'?'pass':'fail',detail:env.verificationEnforcement==='on'?'on · shipper/driver verification enforced':'off · API environment override detected'},
   {key:'routing',label:'Road routing',status:env.mapboxConfigured?'pass':'warn',detail:env.mapboxConfigured?'Mapbox token configured':'Mapbox token missing'},
   {key:'payments',label:'Payments',status:env.paymentsMode==='mock'?'warn':'pass',detail:String(env.paymentsMode)},
   {key:'payouts',label:'Payouts',status:env.payoutsMode==='sandbox'?'warn':'pass',detail:String(env.payoutsMode)},
   {key:'kyc',label:'KYC mode',status:env.kycMode==='mock'?'warn':'pass',detail:String(env.kycMode)},
   {key:'legal',label:'Legal package',status:LEGAL_DOCUMENTS.length>=8?'pass':'fail',detail:`${LEGAL_DOCUMENTS.length} versioned documents · ${LEGAL_VERSION}`},
   {key:'push',label:'Push outbox',status:Number(push.rows[0]?.failed??0)>0?'warn':'pass',detail:`${Number(push.rows[0]?.pending??0)} pending · ${Number(push.rows[0]?.failed??0)} failed`},
   {key:'client-errors',label:'Client errors 24h',status:Number(errors.rows[0]?.errors24h??0)>10?'warn':'pass',detail:`${Number(errors.rows[0]?.errors24h??0)} / 24h · ${Number(errors.rows[0]?.client_open??0)} client open · ${Number(errors.rows[0]?.server_open??0)} server open`},
  ];
  return {generatedAt:new Date().toISOString(),env,checks,funnel:{users:Number(f.users??0),verified:Number(f.verified??0),cargo:Number(f.cargo??0),trips:Number(f.trips??0),offers:Number(f.offers??0),deals:Number(f.deals??0),completed:Number(f.completed??0)},errors:errors.rows[0],push:push.rows[0],legal:{version:LEGAL_VERSION,documents:LEGAL_DOCUMENTS.length,acceptances:legal.rows},privacy:{open:Number(privacy.rows[0]?.open??0)},audit:audit.rows};
 }
}
