import path from 'node:path';
import { config } from 'dotenv';
import { Pool, PoolClient } from 'pg';
import { hashPassword } from '../apps/api/src/auth/password';
import { LEGAL_VERSION } from '../apps/api/src/legal/legal.documents';

config({path:path.resolve(process.cwd(),'.env')});
const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL missing in .env');
if((process.env.NODE_ENV??'development').toLowerCase()==='production')throw new Error('DEMO/STAGING commands are disabled when NODE_ENV=production');
const pool=new Pool({connectionString:url});
const U={reviewer:'18000000-0000-4000-8000-000000000001',sender:'18000000-0000-4000-8000-000000000002',driver:'18000000-0000-4000-8000-000000000003'};
const V='18000000-0000-4000-8000-000000000010';
const ids=(n:number)=>({cargo:`18000000-0000-4000-8000-0000000001${n}1`,trip:`18000000-0000-4000-8000-0000000001${n}2`,offer:`18000000-0000-4000-8000-0000000001${n}3`,deal:`18000000-0000-4000-8000-0000000001${n}4`});
async function reset(c:PoolClient){for(const n of [1,2,3]){const x=ids(n);await c.query('DELETE FROM finance_ledger_entry WHERE deal_id=$1',[x.deal]);await c.query('DELETE FROM deal_dispute WHERE deal_id=$1',[x.deal]);await c.query('DELETE FROM deal_event WHERE deal_id=$1',[x.deal]);await c.query('DELETE FROM deal_conversation WHERE deal_id=$1',[x.deal]);await c.query('DELETE FROM deal WHERE id=$1',[x.deal]);await c.query('DELETE FROM cargo_offer WHERE id=$1',[x.offer]);await c.query('DELETE FROM trip_match WHERE trip_id=$1 OR cargo_id=$2',[x.trip,x.cargo]);await c.query('DELETE FROM trip WHERE id=$1',[x.trip]);await c.query('DELETE FROM cargo WHERE id=$1',[x.cargo]);}await c.query('DELETE FROM vehicle_verification WHERE vehicle_id=$1',[V]);await c.query('DELETE FROM vehicle WHERE id=$1',[V]);await c.query(`DELETE FROM operating_expense WHERE reference='DEMO-SEED'`);await c.query('DELETE FROM app_user WHERE id=ANY($1::uuid[])',[[U.reviewer,U.sender,U.driver]])}
async function main(){const c=await pool.connect();try{await c.query('BEGIN');await reset(c);const pw=await hashPassword('CargoGoDemo!2026');
 const users=[[U.reviewer,'+380500000081','reviewer@demo.cargogo.local','Demo Reviewer','reviewer'],[U.sender,'+380500000082','sender@demo.cargogo.local','Demo Sender',null],[U.driver,'+380500000083','driver@demo.cargogo.local','Demo Driver',null]];
 for(const [id,phone,email,name,role] of users){await c.query(`INSERT INTO app_user(id,phone_e164,email,display_name,password_hash,status,verification_status,staff_role,email_verified_at) VALUES($1,$2,$3,$4,$5,'active','verified',$6,now())`,[id,phone,email,name,pw,role]);for(const key of ['terms-of-use','privacy-policy'])await c.query(`INSERT INTO legal_acceptance(user_id,document_key,document_version,metadata) VALUES($1,$2,$3,'{"source":"demo_seed"}'::jsonb)`,[id,key,LEGAL_VERSION]);}
 for(const id of [U.sender,U.driver])await c.query(`INSERT INTO identity_verification_profile(user_id,status,document_kind,document_country,document_last4,provider,verified_at) VALUES($1,'verified','id_card','UA','DEMO','manual',now())`,[id]);
 await c.query(`INSERT INTO driver_license_verification(user_id,status,country_code,license_last4,categories,provider,verified_at) VALUES($1,'verified','UA','DEMO',ARRAY['B'],'manual',now())`,[U.driver]);
 await c.query(`INSERT INTO vehicle(id,owner_id,label,body_type,max_payload_kg,cargo_length_cm,cargo_width_cm,cargo_height_cm,verification_status,status,fuel_type,engine_displacement_cc,curb_weight_kg,gross_weight_kg,avg_consumption_per_100) VALUES($1,$2,'Demo Van','van',900,220,140,135,'verified','active','diesel',1998,1650,2600,8.2)`,[V,U.driver]);
 await c.query(`INSERT INTO vehicle_verification(vehicle_id,owner_user_id,status,registration_country,registration_number_masked,vin_last6,make,model,year,color,registration_document_status,insurance_status,provider,verified_at) VALUES($1,$2,'verified','UA','AE •••• CG','D3M0CG','Renault','Trafic',2021,'white','verified','verified','manual',now())`,[V,U.driver]);
 await c.query(`INSERT INTO carrier_profile(user_id,mode,professional_status,accepted_casual_policy_at,policy_version) VALUES($1,'casual','not_requested',now(),2)`,[U.driver]);
 const deals=[{n:1,status:'completed',payment:'released',amount:420000,title:'Ноутбуки для офісу'},{n:2,status:'refunded',payment:'refunded',amount:185000,title:'Коробки з обладнанням'},{n:3,status:'disputed',payment:'captured',amount:275000,title:'Демо вантаж зі спором'}];
 for(const d of deals){const x=ids(d.n);const fee=Math.round(d.amount*.045),carrier=d.amount-fee,acq=Math.round(d.amount*.013),payout=Math.round(carrier*.003),net=fee-acq-payout;await c.query(`INSERT INTO cargo(id,owner_id,title,description,weight_kg,reward_minor,currency,pickup_point,delivery_point,status,pickup_public_label,delivery_public_label,pickup_address_private,delivery_address_private,category,length_cm,width_cm,height_cm) VALUES($1,$2,$3,'Grant demo dataset',120,$4,'UAH',ST_SetSRID(ST_MakePoint(35.8700,48.5300),4326)::geography,ST_SetSRID(ST_MakePoint(35.0500,48.4600),4326)::geography,$5,'Павлоград','Дніпро','Demo pickup','Demo delivery','boxes',80,60,55)`,[x.cargo,U.sender,d.title,d.amount,d.status==='completed'?'delivered':d.status==='refunded'?'cancelled':'matched']);await c.query(`INSERT INTO trip(id,driver_id,vehicle_id,origin,destination,route,departure_from,max_detour_km,status,origin_public_label,destination_public_label,capacity_kg,route_distance_m,route_duration_s,route_source,route_quality,carrier_mode_snapshot,casual_cost_cap_minor,casual_policy_version) VALUES($1,$2,$3,ST_SetSRID(ST_MakePoint(35.87,48.53),4326)::geography,ST_SetSRID(ST_MakePoint(35.05,48.46),4326)::geography,ST_GeomFromText('LINESTRING(35.87 48.53,35.05 48.46)',4326)::geography,now()+interval '1 day',20,$4,'Павлоград','Дніпро',900,78000,4200,'fallback','rough','casual',500000,2)`,[x.trip,U.driver,V,d.status==='completed'?'completed':'published']);await c.query(`INSERT INTO cargo_offer(id,cargo_id,trip_id,cargo_owner_id,driver_id,amount_minor,currency,message,status,carrier_mode_snapshot) VALUES($1,$2,$3,$4,$5,$6,'UAH','Demo offer','accepted','casual')`,[x.offer,x.cargo,x.trip,U.sender,U.driver,d.amount]);await c.query(`INSERT INTO deal(id,cargo_id,trip_id,offer_id,sender_id,driver_id,agreed_amount_minor,currency,status,payment_status,platform_fee_minor,carrier_amount_minor,settlement_status,target_net_margin_minor,estimated_acquiring_fee_minor,estimated_payout_fee_minor,actual_acquiring_fee_minor,actual_payout_fee_minor,platform_net_revenue_minor,actual_net_margin_bps,fee_policy_snapshot,carrier_mode_snapshot,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,'UAH',$8,$9,$10,$11,$12,$13,$14,$15,$14,$15,$16,$17,$18::jsonb,'casual',$19)`,[x.deal,x.cargo,x.trip,x.offer,U.sender,U.driver,d.amount,d.status,d.payment,fee,carrier,d.status==='completed'?'settled':d.status==='refunded'?'settled':'held',Math.round(d.amount*.029),acq,payout,net,Math.round(net/d.amount*10000),JSON.stringify({version:1.7,source:'demo_seed'}),d.status==='completed'?new Date().toISOString():null]);
  const entries:[string,number][]=[['customer_capture',d.amount],['platform_fee',fee],['carrier_payable',carrier],['acquiring_fee',acq],['payout_fee',payout],['platform_net_revenue',net]];if(d.status==='completed')entries.push(['carrier_payout',carrier]);if(d.status==='refunded')entries.push(['customer_refund',d.amount]);for(const [type,amount] of entries)await c.query(`INSERT INTO finance_ledger_entry(deal_id,entry_type,amount_minor,currency,provider,metadata) VALUES($1,$2,$3,'UAH','demo','{"source":"demo_seed"}'::jsonb)`,[x.deal,type,amount]);if(d.status==='disputed')await c.query(`INSERT INTO deal_dispute(deal_id,opened_by,status,reason_code,description) VALUES($1,$2,'open','other','Demo dispute for grant presentation')`,[x.deal,U.sender]);}
 await c.query(`INSERT INTO operating_expense(incurred_on,category,description,amount_minor,currency,reference,created_by) VALUES(CURRENT_DATE,'infrastructure','Demo infrastructure allocation',35000,'UAH','DEMO-SEED',$1),(CURRENT_DATE,'maps','Demo map usage allocation',12000,'UAH','DEMO-SEED',$1)`,[U.reviewer]);await c.query(`INSERT INTO audit_event(actor_user_id,event_type,entity_type,metadata) VALUES($1,'demo.seeded','demo_environment',$2::jsonb)`,[U.reviewer,JSON.stringify({legalVersion:LEGAL_VERSION,deals:3})]);await c.query('COMMIT');console.log('DEMO/STAGING seeded.');console.log('Reviewer: +380500000081 / CargoGoDemo!2026');console.log('Sender:   +380500000082 / CargoGoDemo!2026');console.log('Driver:   +380500000083 / CargoGoDemo!2026');}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();await pool.end()}}
main().catch(e=>{console.error(e);process.exit(1)});
