import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { apiFetch } from '@/api/client';
import { colors, radii, themedStyleSheet } from '@/theme/tokens';
export type CountryOption={code:string;name:string};export type CityOption={id:string;countryCode:string;name:string;lat:number;lng:number};export type SelectedPlace={countryCode:string;countryName:string;cityId:string;cityName:string};

export function LocationPicker({label,value,onChange}:{label:string;value:SelectedPlace|null;onChange:(value:SelectedPlace)=>void}){
  const[countries,setCountries]=useState<CountryOption[]>([]);const[cities,setCities]=useState<CityOption[]>([]);const[open,setOpen]=useState(false);const[step,setStep]=useState<'country'|'city'>('country');const[country,setCountry]=useState<CountryOption|null>(value?{code:value.countryCode,name:value.countryName}:null);const[query,setQuery]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const requestId=useRef(0);
  useEffect(()=>{let active=true;void apiFetch('/locations/countries').then(async response=>{const data=await response.json();if(!active)return;if(!response.ok)throw new Error(data?.message??'Не вдалося завантажити країни');setCountries(Array.isArray(data)?data:[])}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Не вдалося завантажити країни')});return()=>{active=false}},[]);
  useEffect(()=>{if(!open||step!=='city'||!country)return;const id=++requestId.current;const timer=setTimeout(()=>{setLoading(true);setError('');void apiFetch(`/locations/cities?country=${encodeURIComponent(country.code)}&q=${encodeURIComponent(query.trim())}`).then(async response=>{const data=await response.json();if(id!==requestId.current)return;if(!response.ok)throw new Error(data?.message??'Не вдалося завантажити міста');setCities(Array.isArray(data)?data:[])}).catch(e=>{if(id===requestId.current)setError(e instanceof Error?e.message:'Не вдалося завантажити міста')}).finally(()=>{if(id===requestId.current)setLoading(false)})},180);return()=>clearTimeout(timer)},[open,step,country,query]);
  const display=useMemo(()=>value?`${value.cityName}, ${value.countryName}`:'Оберіть країну та місто',[value]);
  const show=()=>{setError('');setQuery('');if(value){setCountry({code:value.countryCode,name:value.countryName});setStep('city')}else{setCountry(null);setStep('country')}setOpen(true)};
  const chooseCountry=(item:CountryOption)=>{setCountry(item);setCities([]);setQuery('');setError('');setStep('city')};
  const chooseCity=(item:CityOption)=>{if(!country)return;onChange({countryCode:country.code,countryName:country.name,cityId:item.id,cityName:item.name});setOpen(false);setStep('country');setQuery('');setError('')};
  return <View><Text style={s.label}>{label}</Text><Pressable onPress={show} style={({pressed})=>[s.trigger,pressed&&s.pressed]}><View style={{flex:1}}><Text numberOfLines={1} style={s.value}>{display}</Text>{value?<Text style={s.meta}>{value.countryCode} · {value.cityId}</Text>:<Text style={s.meta}>Країна → місто</Text>}</View><View style={s.chevron}><Text style={s.chevronText}>⌄</Text></View></Pressable>
    <Modal visible={open} transparent animationType="slide" statusBarTranslucent onRequestClose={()=>setOpen(false)}><View style={s.overlay}><Pressable accessibilityLabel="Закрити вибір локації" style={s.dismissArea} onPress={()=>setOpen(false)}/><View style={s.sheet}><View style={s.grabber}/><View style={s.sheetHeader}><View style={{flex:1}}><Text style={s.kicker}>{step==='country'?'КРОК 1 · КРАЇНА':'КРОК 2 · МІСТО'}</Text><Text style={s.heading}>{step==='country'?'Звідки / куди?':country?.name??'Оберіть місто'}</Text></View><Pressable onPress={()=>setOpen(false)} style={s.closeButton}><Text style={s.closeText}>×</Text></Pressable></View>
      {step==='city'?<View style={s.searchWrap}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} autoFocus autoCorrect={false} placeholder="Пошук міста" placeholderTextColor={colors.muted} style={s.search}/></View>:null}
      {error?<View style={s.errorBox}><Text style={s.errorText}>{error}</Text></View>:null}
      <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:12}}>{step==='country'?countries.map(item=><Pressable key={item.code} onPress={()=>chooseCountry(item)} style={({pressed})=>[s.option,pressed&&s.optionPressed]}><View style={s.flag}><Text style={s.flagText}>{item.code}</Text></View><Text style={s.optionText}>{item.name}</Text><Text style={s.arrow}>→</Text></Pressable>):cities.map(item=><Pressable key={item.id} onPress={()=>chooseCity(item)} style={({pressed})=>[s.option,pressed&&s.optionPressed]}><View style={s.cityMark}/><Text style={s.optionText}>{item.name}</Text><Text style={s.chooseText}>ОБРАТИ</Text></Pressable>)}
      {step==='city'&&loading?<View style={s.state}><ActivityIndicator color={colors.accent}/><Text style={s.stateText}>Завантаження міст…</Text></View>:null}{step==='city'&&!loading&&!error&&cities.length===0?<View style={s.state}><Text style={s.stateText}>Міст не знайдено</Text></View>:null}</ScrollView>
      {step==='city'?<Pressable onPress={()=>{setStep('country');setQuery('');setError('')}} style={s.backButton}><Text style={s.backText}>← ЗМІНИТИ КРАЇНУ</Text></Pressable>:null}
    </View></View></Modal></View>;
}
const s=themedStyleSheet(()=>({label:{color:colors.textSecondary,fontSize:9,fontWeight:'900',letterSpacing:1.15,marginBottom:7,marginTop:5},trigger:{minHeight:62,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surfaceRaised,borderRadius:radii.md,paddingHorizontal:14,paddingVertical:10,marginBottom:10,flexDirection:'row',alignItems:'center'},pressed:{opacity:.68},value:{color:colors.text,fontSize:14,fontWeight:'900'},meta:{color:colors.muted,fontSize:9,marginTop:4},chevron:{width:34,height:34,borderRadius:10,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},chevronText:{color:colors.accent,fontSize:19,fontWeight:'900'},overlay:{flex:1,backgroundColor:colors.overlay,justifyContent:'flex-end'},dismissArea:{flex:1},sheet:{maxHeight:'82%',minHeight:'52%',backgroundColor:colors.surface,borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderBottomWidth:0,borderColor:colors.border,paddingHorizontal:16,paddingTop:8,paddingBottom:16},grabber:{width:44,height:4,borderRadius:2,backgroundColor:colors.borderStrong,alignSelf:'center',marginBottom:14},sheetHeader:{flexDirection:'row',gap:12,alignItems:'center',marginBottom:14},kicker:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.3},heading:{color:colors.text,fontSize:23,fontWeight:'900',marginTop:4},closeButton:{width:38,height:38,borderRadius:12,backgroundColor:colors.surfaceRaised,alignItems:'center',justifyContent:'center'},closeText:{color:colors.text,fontSize:22,lineHeight:24},searchWrap:{height:50,borderWidth:1,borderColor:colors.border,borderRadius:radii.md,backgroundColor:colors.surfaceRaised,flexDirection:'row',alignItems:'center',paddingHorizontal:12,marginBottom:10},searchIcon:{color:colors.muted,fontSize:18,marginRight:8},search:{flex:1,color:colors.text,fontSize:13},errorBox:{padding:11,borderRadius:radii.md,backgroundColor:colors.dangerSoft,marginBottom:8},errorText:{color:colors.danger,fontSize:11},option:{minHeight:58,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:colors.border},optionPressed:{opacity:.55},flag:{width:38,height:30,borderRadius:9,backgroundColor:colors.surfaceRaised,alignItems:'center',justifyContent:'center'},flagText:{color:colors.textSecondary,fontSize:9,fontWeight:'900'},cityMark:{width:9,height:9,borderRadius:5,backgroundColor:colors.accent},optionText:{flex:1,color:colors.text,fontSize:14,fontWeight:'800'},arrow:{color:colors.accent,fontSize:17,fontWeight:'900'},chooseText:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:.8},state:{minHeight:92,alignItems:'center',justifyContent:'center',gap:8},stateText:{color:colors.muted,fontSize:11},backButton:{height:46,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},backText:{color:colors.textSecondary,fontSize:9,fontWeight:'900',letterSpacing:.8}}));
