import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';import { ConfigService } from '@nestjs/config';import { createHash, randomUUID } from 'node:crypto';import { DatabaseService } from '../database/database.service';import type { RequestUser } from '../common/request-user';import { NotificationService } from '../notifications/notification.service';import { VerificationStorageService } from '../verification/verification-storage.service';

type QueryExecutor = { query(text:string,values?:any[]):Promise<{rows:any[]}>; };
@Injectable() export class DisputeService{constructor(private db:DatabaseService,private config:ConfigService,private notifications:NotificationService,private storage:VerificationStorageService){}
async open(u:RequestUser,dealId:string,input:{reasonCode:string;description:string}){return this.db.transaction(async c=>{const d=(await c.query<any>('SELECT * FROM deal WHERE id=$1 FOR UPDATE',[dealId])).rows[0];if(!d)throw new NotFoundException({code:'DEAL_NOT_FOUND',message:'Deal not found'});if(d.sender_id!==u.id&&d.driver_id!==u.id)throw new ForbiddenException({code:'DEAL_FORBIDDEN',message:'Not your deal'});if(!['payment_secured','awaiting_pickup','picked_up','in_transit','arrived','delivered'].includes(d.status))throw new ConflictException({code:'DISPUTE_STATE_INVALID',message:'Dispute is not available in the current deal state'});const existing=(await c.query<any>("SELECT * FROM deal_dispute WHERE deal_id=$1 AND status IN ('open','under_review') FOR UPDATE",[dealId])).rows[0];if(existing)return this.getWithClient(c,u.id,existing.id);const r=await c.query<any>(`INSERT INTO deal_dispute(deal_id,opened_by,reason_code,description) VALUES($1,$2,$3,$4) RETURNING *`,[dealId,u.id,input.reasonCode,input.description]);await c.query("UPDATE deal SET dispute_previous_status=status,status='disputed',settlement_status=CASE WHEN settlement_status='settled' THEN settlement_status ELSE 'manual_review' END,updated_at=now() WHERE id=$1",[dealId]);await c.query(`INSERT INTO deal_event(deal_id,actor_user_id,event_type,from_status,to_status,metadata) VALUES($1,$2,'dispute.opened',$3,'disputed',$4::jsonb)`,[dealId,u.id,d.status,JSON.stringify({reasonCode:input.reasonCode})]);const other=d.sender_id===u.id?d.driver_id:d.sender_id;await this.notifications.create({userId:other,type:'dispute.opened',title:'Відкрито спір',body:'Інша сторона відкрила спір по угоді. Виплата призупинена до рішення.',entityType:'deal',entityId:dealId},c);return this.getWithClient(c,u.id,r.rows[0].id);});}
async mine(u:RequestUser){const r=await this.db.query<any>(`SELECT x.id FROM deal_dispute x JOIN deal d ON d.id=x.deal_id WHERE d.sender_id=$1 OR d.driver_id=$1 ORDER BY x.created_at DESC LIMIT 100`,[u.id]);return Promise.all(r.rows.map((x:any)=>this.get(u,x.id)));}
async get(u:RequestUser,id:string){return this.getWithClient(this.db,u.id,id)}
async forDeal(u:RequestUser,dealId:string){const d=await this.db.query<any>('SELECT id FROM deal WHERE id=$1 AND (sender_id=$2 OR driver_id=$2)',[dealId,u.id]);if(!d.rows[0])throw new NotFoundException({code:'DEAL_NOT_FOUND',message:'Deal not found'});const r=await this.db.query<any>('SELECT id FROM deal_dispute WHERE deal_id=$1 ORDER BY created_at DESC LIMIT 1',[dealId]);return r.rows[0]?this.get(u,r.rows[0].id):null;}
async addEvidence(u:RequestUser,id:string,text:string){return this.db.transaction(async c=>{const x=await this.getWithClient(c,u.id,id);if(!['open','under_review'].includes(x.status))throw new ConflictException({code:'DISPUTE_CLOSED',message:'Dispute no longer accepts evidence'});const r=await c.query<any>(`INSERT INTO dispute_evidence(dispute_id,submitted_by,kind,text_content) VALUES($1,$2,'note',$3) RETURNING *`,[id,u.id,text]);return {id:Number(r.rows[0].id),kind:'note',text:r.rows[0].text_content,isMine:true,createdAt:r.rows[0].created_at};});}
async addPhoto(u:RequestUser,id:string,note:string|undefined,file:{buffer:Buffer;mimetype:string;size:number}){const x=await this.get(u,id);if(!['open','under_review'].includes(x.status))throw new ConflictException({code:'DISPUTE_CLOSED',message:'Dispute no longer accepts evidence'});const mime=(file.mimetype??'').split(';')[0].toLowerCase();if(!['image/jpeg','image/png'].includes(mime)||this.storage.detectMime(file.buffer)!==mime)throw new BadRequestException({code:'DISPUTE_PHOTO_INVALID',message:'Only valid JPEG or PNG photos are accepted'});if(file.buffer.length>10*1024*1024)throw new BadRequestException({code:'DISPUTE_PHOTO_TOO_LARGE',message:'Photo must be 10 MB or smaller'});const count=await this.db.query<{count:string}>(`SELECT count(*)::text count FROM dispute_evidence WHERE dispute_id=$1 AND submitted_by=$2 AND kind='photo'`,[id,u.id]);if(Number(count.rows[0]?.count??0)>=3)throw new ConflictException({code:'DISPUTE_PHOTO_LIMIT',message:'Each side can add up to 3 dispute photos'});const key=`dispute-evidence/${id}/${u.id}/${randomUUID()}.${mime==='image/png'?'png':'jpg'}`;await this.storage.putObject(key,file.buffer,mime);try{const r=await this.db.query<any>(`INSERT INTO dispute_evidence(dispute_id,submitted_by,kind,text_content,object_key) VALUES($1,$2,'photo',$3,$4) RETURNING *`,[id,u.id,note?.trim()||null,key]);return{id:Number(r.rows[0].id),kind:'photo',text:r.rows[0].text_content,isMine:true,createdAt:r.rows[0].created_at};}catch(e){await this.storage.deleteObject(key).catch(()=>{});throw e}}
async evidenceAccess(u:RequestUser,id:string,evidenceId:number,purpose:string){const participant=await this.db.query<any>(`SELECT e.object_key FROM dispute_evidence e JOIN deal_dispute x ON x.id=e.dispute_id JOIN deal d ON d.id=x.deal_id WHERE e.id=$1 AND x.id=$2 AND (d.sender_id=$3 OR d.driver_id=$3 OR $4)`,[evidenceId,id,u.id,(u.staffRole==='reviewer'||u.staffRole==='dispute_reviewer'||u.staffRole==='admin')]);const e=participant.rows[0];if(!e?.object_key)throw new NotFoundException({code:'DISPUTE_EVIDENCE_NOT_FOUND',message:'Evidence photo not found'});await this.db.query(`INSERT INTO dispute_evidence_access_log(evidence_id,actor_user_id,purpose) VALUES($1,$2,$3)`,[evidenceId,u.id,purpose]);return{url:this.storage.presign('GET',e.object_key,300),expiresInSeconds:300}}
private assertDisputeReviewer(u:RequestUser){if(u.staffRole!=='reviewer'&&u.staffRole!=='dispute_reviewer'&&u.staffRole!=='admin')throw new ForbiddenException({code:'DISPUTE_REVIEWER_REQUIRED',message:'Dispute reviewer role required'})}
async reviewQueue(u:RequestUser){this.assertDisputeReviewer(u);const r=await this.db.query<any>(`SELECT x.id,x.deal_id AS "dealId",x.reason_code AS "reasonCode",x.status,x.created_at AS "createdAt",su.display_name AS "senderName",du.display_name AS "driverName" FROM deal_dispute x JOIN deal d ON d.id=x.deal_id JOIN app_user su ON su.id=d.sender_id JOIN app_user du ON du.id=d.driver_id WHERE x.status IN ('open','under_review') ORDER BY x.created_at ASC LIMIT 100`);return r.rows}
async claim(u:RequestUser,id:string){this.assertDisputeReviewer(u);const r=await this.db.query<any>(`UPDATE deal_dispute SET status='under_review',reviewed_by=$2,review_started_at=COALESCE(review_started_at,now()),updated_at=now() WHERE id=$1 AND status IN ('open','under_review') AND (reviewed_by IS NULL OR reviewed_by=$2) RETURNING id`,[id,u.id]);if(!r.rows[0])throw new ConflictException({code:'DISPUTE_ALREADY_CLAIMED',message:'Dispute is being reviewed by another reviewer'});return this.reviewDetail(u,id)}
async reviewDetail(u:RequestUser,id:string){this.assertDisputeReviewer(u);const r=await this.db.query<any>(`SELECT x.*,d.sender_id,d.driver_id,d.declared_value_minor_snapshot,d.declared_value_currency_snapshot,s.display_name sender_name,dr.display_name driver_name FROM deal_dispute x JOIN deal d ON d.id=x.deal_id JOIN app_user s ON s.id=d.sender_id JOIN app_user dr ON dr.id=d.driver_id WHERE x.id=$1`,[id]);const x=r.rows[0];if(!x)throw new NotFoundException();const e=await this.db.query<any>(`SELECT id,submitted_by,kind,text_content,created_at FROM dispute_evidence WHERE dispute_id=$1 ORDER BY created_at`,[id]);const h=await this.db.query<any>(`SELECT id,stage,mime_type,size_bytes,sha256_hex,note,server_captured_at,latitude,longitude,accuracy_meters,client_captured_at,location_status,participant_role,synchronization_grade FROM deal_handover_evidence WHERE deal_id=$1 ORDER BY server_captured_at`,[x.deal_id]);const handoverAssessment=this.assessHandover(h.rows);const problem=await this.db.query<any>(`SELECT reason,note,latitude,longitude,accuracy_meters,client_location_at,location_status,server_reported_at FROM deal_delivery_confirmation_problem WHERE deal_id=$1`,[x.deal_id]);return{id:x.id,dealId:x.deal_id,reasonCode:x.reason_code,description:x.description,status:x.status,declaredValueMinor:x.declared_value_minor_snapshot==null?null:Number(x.declared_value_minor_snapshot),declaredValueCurrency:x.declared_value_currency_snapshot??null,sender:{id:x.sender_id,name:x.sender_name},driver:{id:x.driver_id,name:x.driver_name},evidence:e.rows,handoverEvidence:h.rows.map((z:any)=>({id:z.id,stage:z.stage,participantRole:z.participant_role??null,synchronizationGrade:z.synchronization_grade??null,mimeType:z.mime_type,sizeBytes:Number(z.size_bytes),sha256:z.sha256_hex,note:z.note,capturedAt:z.server_captured_at,locationStatus:z.location_status??'unavailable',location:z.latitude==null||z.longitude==null?null:{latitude:Number(z.latitude),longitude:Number(z.longitude),accuracyMeters:z.accuracy_meters==null?null:Number(z.accuracy_meters),clientCapturedAt:z.client_captured_at??null}})),handoverAssessment,deliveryConfirmationProblem:problem.rows[0]??null,createdAt:x.created_at}}
async resolveReview(u:RequestUser,id:string,winner:'sender'|'driver',note:string){this.assertDisputeReviewer(u);return this.resolveInternal(u,id,winner,note,true)}

private assessHandover(rows:any[]){
  const delivery=rows.filter((r:any)=>r.stage==='delivery');
  const first=(role:string)=>delivery.filter((r:any)=>r.participant_role===role).sort((a:any,b:any)=>new Date(a.server_captured_at).getTime()-new Date(b.server_captured_at).getTime())[0]??null;
  const driver=first('driver'),sender=first('sender');
  if(!driver||!sender)return{grade:'REVIEW',photoDeltaSeconds:null,locationDistanceMeters:null,locationConsistent:null,reason:'BOTH_FIRST_PHOTOS_REQUIRED'};
  const delta=Math.abs(new Date(driver.server_captured_at).getTime()-new Date(sender.server_captured_at).getTime())/1000;
  let distance:number|null=null,consistent:boolean|null=null;
  if(driver.latitude!=null&&driver.longitude!=null&&sender.latitude!=null&&sender.longitude!=null){
    const rad=(v:number)=>v*Math.PI/180,R=6371000,dLat=rad(Number(sender.latitude)-Number(driver.latitude)),dLon=rad(Number(sender.longitude)-Number(driver.longitude));
    const a=Math.sin(dLat/2)**2+Math.cos(rad(Number(driver.latitude)))*Math.cos(rad(Number(sender.latitude)))*Math.sin(dLon/2)**2;
    distance=2*R*Math.asin(Math.sqrt(a));
    const tolerance=Math.max(50,Number(driver.accuracy_meters??0)+Number(sender.accuracy_meters??0)+25); consistent=distance<=tolerance;
  }
  let grade:'STRONG'|'REVIEW'|'WEAK';
  if(consistent===false||delta>120)grade='WEAK'; else if(delta<=60&&consistent===true)grade='STRONG'; else grade='REVIEW';
  return{grade,photoDeltaSeconds:Math.round(delta),locationDistanceMeters:distance==null?null:Math.round(distance),locationConsistent:consistent,driverAccuracyMeters:driver.accuracy_meters==null?null:Math.round(Number(driver.accuracy_meters)),senderAccuracyMeters:sender.accuracy_meters==null?null:Math.round(Number(sender.accuracy_meters)),reason:grade==='STRONG'?'SYNCHRONIZED_AND_COLOCATED':consistent===false?'LOCATION_MISMATCH':delta>120?'PHOTO_DELTA_LATE':'MANUAL_CONTEXT_RECOMMENDED'};
}
private async resolveInternal(u:RequestUser,id:string,winner:'sender'|'driver',note:string,admin:boolean){return this.db.transaction(async c=>{const q=await c.query<any>('SELECT x.*,d.sender_id,d.driver_id,d.cargo_id FROM deal_dispute x JOIN deal d ON d.id=x.deal_id WHERE x.id=$1 FOR UPDATE',[id]);const x=q.rows[0];if(!x)throw new NotFoundException();if(!['open','under_review'].includes(x.status))throw new ConflictException({code:'DISPUTE_CLOSED',message:'Dispute already resolved'});const ds=winner==='sender'?'resolved_sender':'resolved_driver';await c.query('UPDATE deal_dispute SET status=$2,resolution_code=$3,resolution_note=$4,resolved_at=now(),reviewed_by=COALESCE(reviewed_by,$5),updated_at=now() WHERE id=$1',[id,ds,winner,note,admin?u.id:null]);if(winner==='sender'){await c.query("UPDATE deal SET status='refunded',payment_status='refunded',settlement_status='settled',updated_at=now() WHERE id=$1",[x.deal_id]);await c.query("UPDATE cargo SET status='cancelled',updated_at=now() WHERE id=$1",[x.cargo_id]);}else{await c.query("UPDATE deal SET status='completed',payment_status='released',settlement_status='settled',completed_at=COALESCE(completed_at,now()),updated_at=now() WHERE id=$1",[x.deal_id]);await c.query("UPDATE cargo SET status='delivered',updated_at=now() WHERE id=$1",[x.cargo_id]);}for(const userId of [x.sender_id,x.driver_id])await this.notifications.create({userId,type:'dispute.resolved',title:'Спір вирішено',body:winner==='sender'?'Рішення на користь відправника.':'Рішення на користь перевізника.',entityType:'deal',entityId:x.deal_id},c);return{ok:true,status:ds,winner,note}})}
private async getWithClient(c:QueryExecutor,userId:string,id:string){const r=await c.query(`SELECT x.*,d.sender_id,d.driver_id FROM deal_dispute x JOIN deal d ON d.id=x.deal_id WHERE x.id=$1 AND (d.sender_id=$2 OR d.driver_id=$2)`,[id,userId]);const x=r.rows[0];if(!x)throw new NotFoundException({code:'DISPUTE_NOT_FOUND',message:'Dispute not found'});const e=await c.query('SELECT id,submitted_by,kind,text_content,created_at FROM dispute_evidence WHERE dispute_id=$1 ORDER BY created_at ASC',[id]);const handover=await c.query('SELECT id,stage,mime_type,size_bytes,sha256_hex,note,server_captured_at,latitude,longitude,accuracy_meters,client_captured_at,location_status FROM deal_handover_evidence WHERE deal_id=$1 ORDER BY server_captured_at ASC',[x.deal_id]);return{id:x.id,dealId:x.deal_id,reasonCode:x.reason_code,description:x.description,status:x.status,resolutionNote:x.resolution_note,openedByMe:x.opened_by===userId,createdAt:x.created_at,resolvedAt:x.resolved_at,evidence:e.rows.map((z:any)=>({id:Number(z.id),kind:z.kind,text:z.text_content,isMine:z.submitted_by===userId,createdAt:z.created_at})),handoverEvidence:handover.rows.map((z:any)=>({id:z.id,stage:z.stage,mimeType:z.mime_type,sizeBytes:Number(z.size_bytes),sha256:z.sha256_hex,note:z.note,capturedAt:z.server_captured_at,locationStatus:z.location_status??'unavailable',location:z.latitude==null||z.longitude==null?null:{latitude:Number(z.latitude),longitude:Number(z.longitude),accuracyMeters:z.accuracy_meters==null?null:Number(z.accuracy_meters),clientCapturedAt:z.client_captured_at??null}}))}}
}
